### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_syslog#1]
I pulled this down and tried to install it under the latest 1.0.0 Cacti dev branch (commit 2e51456). When I go to plugin managment, it shows in the list, but the only option listed is "Install Old Plugin" under actions when hovering over the gear icon. Clicking on the action gear does nothing.

**Comment by cigamit** [comment]
did you have syslog installed previously?  it this a new install or an upgrade of an old system?

**Comment by cigamit** [comment]
please run the following sql command:
update plugin_config set status=0 where directory='syslog';
then refresh plugin management page.  this would had to have been an upgrade, which is currently not supported due to the scope of the changes.  you should also drop all your syslog tables before you do the install or there may be other problems.

**Comment by smiles1969** [comment]
On this box it is new install. This box is slated as dev for testing.

I am running another box with an older version of your plugin (v1.4), also running cacti 1.0.0 at an older commit version.

**Comment by smiles1969** [comment]
mysql> update plugin_config set status=0 where directory='syslog';
Query OK, 0 rows affected (0.00 sec)
Rows matched: 0  Changed: 0  Warnings: 0

mysql> select * from plugin_config;
Empty set (0.00 sec)

mysql> describe plugin_config;
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type         | Null | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| id        | int(8)       | NO   | PRI | NULL    | auto_increment |
| directory | varchar(32)  | NO   | MUL |         |                |
| name      | varchar(64)  | NO   |     |         |                |
| status    | tinyint(2)   | NO   | MUL | 0       |                |
| author    | varchar(64)  | NO   |     |         |                |
| webpage   | varchar(255) | NO   |     |         |                |
| version   | varchar(8)   | NO   |     |         |                |
+-----------+--------------+------+-----+---------+----------------+

**Comment by cigamit** [comment]
okay, that is interesting.  taking a closer look.

**Comment by cigamit** [comment]
can you check on the permissions of the syslog directory and files and make sure the web account can read setup.php properly?  Also, set error_log = /tmp/debug.log in php.ini and load the page again after your restart apache/nginx and see if there are errors in that file after page load.

**Comment by cigamit** [comment]
just updated the setup.php.  though by doing a code review, there is something else contributing to the problem.  I'm thinking permissions, suhosin, memory limits, or some other issue corner case.

**Comment by smiles1969** [comment]
Looks like the directory is looking for syslog not plugin_syslog. I’m seeing this:

root@ctcv-cacti2:/var/www/html/cacti/plugins/plugin_syslog# tail -f /tmp/php_debug.log
[17-May-2016 15:55:02 America/Chicago] PHP Warning:  include_once(/var/www/html/cacti/plugins/syslog/database.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/plugin_syslog/setup.php on line 15
[17-May-2016 15:55:02 America/Chicago] PHP Warning:  include_once(): Failed opening '/var/www/html/cacti/plugins/syslog/database.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/cacti/plugins/plugin_syslog/setup.php on line 15

From setup.php:

include_once($config['base_path'] . '/plugins/syslog/database.php');

Should I just rename the plugin directory or should the include have a variable for the directory?

**Comment by cigamit** [comment]
I would have never thought of that honestly.  that is indeed the problem.  rename the directory, and try again.  feel free to close this issue.

**Comment by smiles1969** [comment]
Thanks for the help :)
