### ISSUE TITLE
Add Body Text to Alert email

### ISSUE THREAD

**Issue by xmacan** [Cacti/plugin_syslog#108]
Syslog report rule has "Report Body Text" which is displayed in mail. I'm thinking about the same thing in alerts. 

My syslog plugin sends alerts to customers (they only receiving emails, no access to cacti) and I need add information for few alerts. 

If it is meaningful for you, let me know and I will prepare pull request.

**Comment by TheWitness** [comment]
Please prepare a pull request.  Thanks!!

**Comment by TheWitness** [comment]
Test it when you get a chance.  But it's fixed now.
