### ISSUE TITLE
Syslog Alerts cause DB errors

### ISSUE THREAD

**Issue by sunagui** [Cacti/plugin_syslog#110]
When setting up a syslog alert, I get the following errors when triggered:
![Cacti_syslog_alert_errors](https://user-images.githubusercontent.com/61474732/75280155-e8e48980-57da-11ea-8462-04e7ce75f7a6.png)
And these are the alert settings:
![Cacti_syslog_alert_errors2](https://user-images.githubusercontent.com/61474732/75280322-352fc980-57db-11ea-8c29-7cd822f2fe2e.png)

**Comment by jotate-git** [comment]
I am also experiencing the same issue

**Comment by TheWitness** [comment]
This is resolved now.
