### ISSUE TITLE
Can not load host table when use different syslog server

### ISSUE THREAD

**Issue by sank007** [Cacti/plugin_syslog#111]
can not load host when use different syslog server

2020/02/27 09:57:14 - CMDPHP ERROR: A DB Row Failed!, Error: Table 'cacti_syslog.host' doesn't exist
--

syslog.php
host in cacti is in another server can not join

								$hosts = syslog_db_fetch_assoc("SELECT sh.host_id, sh.host, h.id
									FROM `" . $syslogdb_default . "`.`syslog_hosts` AS sh
									LEFT JOIN host AS h
									ON sh.host = h.hostname
									OR sh.host = h.description
									OR sh.host LIKE substring_index(h.hostname, '.', 1)
									OR sh.host LIKE substring_index(h.description, '.', 1)
									$hosts_where
									ORDER BY host");

**Comment by TheWitness** [comment]
That's a bummer.  Checking into it now.

**Comment by TheWitness** [comment]
This should be fixed now.
