### ISSUE TITLE
Issue with 2.7 cacti shutdown handler

### ISSUE THREAD

**Issue by jotate-git** [Cacti/plugin_syslog#112]
I installed v 2.7 of syslog 
-removed all syslog plugin files
-uninstalled syslog plugin via cacti web ui (removed all settings and tables)
-copied syslog 2.7 files to syslog plugin dir
-installed syslog via cacti web UI

Syslog installs, but when upon access the sylsog tab, error 500 window pops up.  attaching error screenshot  from cacti log
![New Bitmap Image](https://user-images.githubusercontent.com/61281357/75631850-638b1b80-5bc4-11ea-94ae-fa31672e14a2.jpg)

**Comment by TheWitness** [comment]
Looks almost like you $CACTI_TOP/plugins/syslog/database.php is not readable by the web server.

**Comment by TheWitness** [comment]
Oh, looks like I'm still pretty rusty at this.  Missed a file.  I'm going to re-cut the release as soon as it's uploaded.

**Comment by jotate-git** [comment]
> 
> 
> Oh, looks like I'm still pretty rusty at this. Missed a file. I'm going to re-cut the release as soon as it's uploaded.

Thanks again for your your assistance!

**Comment by TheWitness** [comment]
Okay, just download the release again.  It has the missing update now.

**Comment by jotate-git** [comment]
> 
> 
> Okay, just download the release again. It has the missing update now.

it appears issue still exists, 


2020/03/01 14:14:43 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'syslog'
--
2020/03/01 14:14:43 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/03/01 14:14:43 - ERROR PHP ERROR in  Plugin 'syslog': Call to  undefined function syslog_db_fetch_assoc() in file:  /usr/share/cacti/plugins/syslog/syslog.php on line: 984



020/03/01 14:14:36 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'syslog'
--
2020/03/01 14:14:36 - CMDPHP PHP ERROR Backtrace:  (CactiShutdownHandler())
2020/03/01 14:14:36 - ERROR PHP ERROR in  Plugin 'syslog': Call to  undefined function syslog_db_table_exists() in file:  /usr/share/cacti/plugins/syslog/syslog.php on line: 1324

**Comment by TheWitness** [comment]
I pushed the release again.  Still figuring out things in GitHub.

**Comment by jotate-git** [comment]
> 
> 
> I pushed the release again. Still figuring out things in GitHub.

thanks sir!  I will test sometime tomorrow, and post feedback.

**Comment by jotate-git** [comment]
> 
> 
> I pushed the release again. Still figuring out things in GitHub.

just tested newest 2.7 release.  all seems good to go thus far.  thanks again!
