### ISSUE TITLE
Some field where not corrected following the version change

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_syslog#115]
I the new 2.7 syslog the table field change:
date and time become logtime, but on functions.php there is a lot with the old filed definition, and give this error:
05/03/2020 13:16:03 - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php[258]:syslog_remove_items(), /plugins/syslog/functions.php[493]:syslog_db_execute(), /plugins/syslog/database.php[57]:db_execute(), /lib/database.php[210]:db_execute_prepared())
05/03/2020 13:16:03 - CMDPHP ERROR: A DB Exec Failed!, Error: Unknown column 'si.date' in 'field list'

**Comment by TheWitness** [comment]
Okay, this is fixed now.
