### ISSUE TITLE
Can not send mail for syslog alert using default From mail user 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_syslog#119]
1) Add a syslog alert rule and trigger it, make it send mail to a user 
2) Error exist in log 

2020/03/27  01:35:04 - CMDPHP MAILER ERROR Backtrace:   (/plugins/syslog/syslog_process.php[422]:syslog_sendemail(),  /plugins/syslog/functions.php[53]:mailer(),  /lib/functions.php[3527]:record_mailer_error(),  /lib/functions.php[3733]:cacti_debug_backtrace())
--
2020/03/27 01:35:04 - CMDPHP MAILER ERROR: Invalid address:  (From): root@localhost

If does not set From Email Address under Configuration - Settings - Mail/Reporting/DNS, using default  from mail user will get this problem 

rhel8.2 x64 
Cacti 1.2.10
Syslog 2.7 
FF 74

**Comment by TheWitness** [comment]
This is a Cacti issue and will be fixed there.

**Comment by ddb4github** [comment]
syslog_process.php use default `root@localhost` like thold `Cacti@localhost`

**Comment by TheWitness** [comment]
Pull request would be fine.
