### ISSUE TITLE
XSS Vulnerabilities under Console->Syslog xxx

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_syslog#125]
## Describe the bug
Syslog alert/removal/report popup alert during XSS testing.

### Case#1
1. Create a Syslog Alert, input `<script>alert('test CVE');</script>` for all text/area fields
2. Click Save button, and return to list page
3. `alert` will popup three times, as screenshot below.
![image](https://user-images.githubusercontent.com/17589018/81493443-f934dc80-92d2-11ea-9c0d-bb633182d6bf.png)

### Case#2
1.  Create a Syslog Alert(or Removal, Report).
2. Input `<script>alert('test CVE');</script>`  in name field.
3. Click Save button, and return list page,
4. Click list item, and select one.
5. Select `Delete` from action list
6. Click `Go`
7. `alert` popup

**Comment by netniV** [comment]
This should have a CVE recorded for it, can you get one?

**Comment by ddb4github** [comment]
> This should have a CVE recorded for it, can you get one?

Request CVE ID yesterday. still not reviewed now

**Comment by netniV** [comment]
Is this the same CVE as the core or a separate one for the plugin?

**Comment by ddb4github** [comment]
> Is this the same CVE as the core or a separate one for the plugin?

I plan to request separate CVE ID for syslog/thold once the my first CVE ID processed.
But the first one is still under review. I'm not sure if any program issue.
