### ISSUE TITLE
Email HTML not working

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_syslog#13]
When Syslog send mail on HTML format, I recieved HTML code, not HTML mail.

`.body { font-size:12pt; font-family:Verdana,Arial,Helvetica,sans-serif; } .table { align:center; width:100%; } .table tr th.th { background: rgba(138,179,105,1); background: -moz-linear-gradient(top, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%); background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(138,179,105,1)), color-stop(100%, rgba(63,117,15,1))); background: -webkit-linear-gradient(top, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%); background: -o-linear-gradient(top, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%); background: -ms-linear-gradient(top, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%); background: linear-gradient(to bottom, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%); filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#8ab369', endColorstr='#3f750f', GradientType=0 ); } .th { color: snow; font-weight:bold; vertical-align:bottom; text-align:left; } .td { color:black; font-family:Verdana,Arial,Helvetica,sans-serif; text-align:left; } .h1 { text-align:center; font-family:Verdana,Arial,Helvetica,sans-serif; font-size:16pt; } .p { text-align:left; font-family:Verdana,Arial,Helvetica,sans-serif; font-size:12pt; } Cacti Syslog Plugin Threshold Alert 'IPMB'Alert NameSeverityThresholdCountMatch StringIPMB Notice 1 5 Unauthenticated IP-MAC address and discarded by IMPB HostnameDateSeverityPriotityMessage172.18.101.122 2017-01-22 20:03:08 Notice 4 Unauthenticated IP-MAC address and discarded by IMPB(IP:, MAC:, Port) 172.18.103.94 2017-02-08 10:30:38 Notice 4 Unauthenticated IP-MAC address and discarded by IMPB(IP:, MAC:, Port) 172.18.103.97 2017-02-08 10:30:38 Notice 4 Unauthenticated IP-MAC address and discarded by IMPB(IP:, MAC:, Port) 172.18.101.127 2017-02-08 10:30:37 Notice 4 Unauthenticated IP-MAC address and discarded by IMPB(IP:, MAC:, Port) 172.18.101.127 2017-02-08 10:30:37 Notice 4 Unauthenticated IP-MAC address and discarded by IMPB(IP:, MAC:, Port)`

Also mail recived from root user and email adress. From Email Address and From Display Name  not working.

**Comment by cigamit** [comment]
Resolved.  Please test.  Did not resolved the 'root' user issue, just html email.

**Comment by pautiina** [comment]
Mail recieved on HTML, but have new error:
```
2017-02-08 14:23:19 - ERROR PHP NOTICE: Undefined variable: headers in file: /var/www/cacti/lib/functions.php  on line: 3573
2017-02-08 14:23:19 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/syslog/syslog_process.php: 381 syslog_sendemail)(/plugins/syslog/functions.php: 59 mailer)(/lib/functions.php: 3573 CactiErrorHandler)(/lib/functions.php: 4238 cacti_debug_backtrace)
2017-02-08 14:23:25 - MAILER Mail Sucessfully Sent to 'pautina@kharkiv.net', Subject: 'Event Alert - Test'
2017-02-08 14:23:25 - SYSLOG WARNING: The Syslog Alert 'Test' with Severity 'Notice', has been Triggered on Host 'noc', and Sequence '1737'
2017-02-08 14:23:25 - ERROR PHP WARNING: Missing argument 9 for mailer(), called in /var/www/cacti/plugins/syslog/functions.php on line 59 and defined in file: /var/www/cacti/lib/functions.php  on line: 3350
2017-02-08 14:23:25 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/syslog/syslog_process.php: 381 syslog_sendemail)(/plugins/syslog/functions.php: 59 mailer)(/lib/functions.php: 3350 CactiErrorHandler)(/lib/functions.php: 4233 cacti_debug_backtrace)
2017-02-08 14:23:25 - ERROR PHP WARNING: Missing argument 10 for mailer(), called in /var/www/cacti/plugins/syslog/functions.php on line 59 and defined in file: /var/www/cacti/lib/functions.php  on line: 3350
```
and mail HTML no support UTF-8
![11](https://cloud.githubusercontent.com/assets/11805503/22737215/c7ff2a78-ee0a-11e6-9a80-2b89a839f1f8.png)

**Comment by cigamit** [comment]
Update lib/function.php.  Should be resolved now.

**Comment by pautiina** [comment]
I think the line 59 must be:
`mailer($from, $nonsms, '', '', '', $subject, $message, '', '', '', __('Please use an HTML Email Client'));`
and the line 62:
mailer($from, $nonsms, '', '', '', $subject, $message, '', '', '', '');

**Comment by pautiina** [comment]
> Update lib/function.php. Should be resolved now.

Nothing change

**Comment by pautiina** [comment]
Mail sent not full information:
![12](https://cloud.githubusercontent.com/assets/11805503/22738619/d768bda2-ee10-11e6-9598-f1249d50508e.png)
On database have:
`'Unauthenticated IP-MAC address and discarded by IMPB(IP:<192.168.0.1>, MAC:<14-CC-20-88-59-13>, Port<4>)'`

**Comment by cigamit** [comment]
Just updated lib/functions.php.  Try again.  I'm noticing the header that was UTF-8 is not translating properly.  We'll keep working on this one.

**Comment by cigamit** [comment]
If it does not work with the latest lib/functions.php, try removing the htmlspecialchars() function on line 328.

**Comment by pautiina** [comment]
UTF-8 now working.

**Comment by pautiina** [comment]
I cannot find htmlspecialchars() function on line 328

**Comment by pautiina** [comment]
Removing the htmlspecialchars() function on line 328 in file syslog_process.php not help me. Some message, that have specialchars not full.

**Comment by cigamit** [comment]
Try again.

**Comment by pautiina** [comment]
I'm sorry, I looked the source code and the letter it turns out that message comes complete, but due to the fact that the report contains special characters "<" in the browser, this part is not displayed.
Source code of the letter:
```
<tr><td class=3D'td'>172.18.10=
3.97</td>=0A<td class=3D'td'>2017-02-09 10:18:39</td>=0A<td class=3D'td'>No=
tice</td>=0A<td class=3D'td'>warn</td>=0A<td class=3D'td'>Unauthenticated I=
P-MAC address and discarded by IMPB(IP:<*hide.*hide.80.62>, MAC:<C0-4A-00-BA-86-=
D1>, Port<25>)</td></tr>
```
Source code HTML:
```
<tr><td class="td">172.18.103.97</td>
<td class="td">2017-02-09 10:18:39</td>
<td class="td">Notice</td>
<td class="td">warn</td>
<td class="td">Unauthenticated IP-MAC address and discarded by IMPB(IP:, MAC:<!-- c0-4a-00-ba-86-d1 ignored -->, Port)</td></tr>
```
I change in file syslog_process.php on line 359:
`							$htmlm  .= "<td class='td'>"     . $a['message']                   . "</td></tr>" . "\n";
`
to this:
`                                                        $htmlm  .= "<td class='td'>"     . htmlspecialchars($a['message'])    . "</td></tr>" . "\n";`

Now mail whith HTML show full message.

**Comment by cigamit** [comment]
Okay, I missed some entire sections, all good now.

**Comment by pautiina** [comment]
HTML format now working good, but From email adress not correct. All message from Syslog plugin comes from Cacti@cacti.net

**Comment by cigamit** [comment]
Corrected.  Please update.  There is no longer a setting on the syslog tabl for from name and email.  It's all under the Mail/Reporting/DNS Settings tab.

**Comment by pautiina** [comment]
It's working. Thanks.
