### ISSUE TITLE
Syslog plugin will break remote collectors if DB is not present

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_syslog#135]
Hey Everyone 

I just found this 

If you have remote collectors and you enable the syslog plugin the config.php file will be moved over via resource cache
once that happens the plugin will look for that DB in my case the DB was local to the main poller and the remotes were looking for the DB 

You will see this when you go to the web interface of the remote poller top left you will see a message cannot connect
the interface will not work however polling seems to be unimpacted but other things such as realtime I am guessing because of the web call will fail when a device is associated to the remote poller

**Comment by bmfmancini** [comment]
since there are remote collectors the plugin, replicates over config.php which also tries to connect to a localhost db unless you are going to have a syslog db on each server you would need to point it to the real db

I am going to try to put nosync in the INFO file to prevent the changes of config.php to replicate to the remote pollers which should allow me to have the remote pollers point back to the main pollers Syslog db

This of course is not a problem if the syslog db is on a completely different server than your cacti cluster then all of the servers would point to that server and not have this problem

**Comment by TheWitness** [comment]
Hmm, config.php is supposed to be skipped.  Let me check that.

**Comment by TheWitness** [comment]
Well, the only time that this will be a problem is if the main server is not reachable as syslog will attempt to connect back to your main cacti server from the remote.  So, I think that's the real bug, if the main server is down, bad things will happen.

**Comment by TheWitness** [comment]
This is resolved now.
