### ISSUE TITLE
Syslog install with option 'upgrade_type=truncate' removes records from table syslog_alert and syslog_remove

### ISSUE THREAD

**Issue by kim-fitness** [Cacti/plugin_syslog#138]
1. Set $syslog_install_options['upgrade_type'] = 'truncate' in config.php
2. Add record in table syslog_alert
3. Uninstall syslog plugin by option 'Syslog Data Only'
4. Check record in table syslog_alert, it exists.
5. Install syslog plugin
6. Check record in table syslog_alert, it is removed.

**Comment by TheWitness** [comment]
@kim-fitness, I've closed the pull request as the function call that is being made is designed for new installs and not upgrades.  I suggest you propose something different "truncate" means just that.  If you are upgrading and you wish to truncate, it's going to recreate all the tables from scratch.  So, it's working as designed.  If you wish for those tables to stay put, you have to switch the upgrade option to something else other than truncate in your option array.
