### ISSUE TITLE
[SYSLOG PLUGIN] latest - PHP ERROR

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_syslog#144]
With latest plugin code i have experience this error when an alarm is raised:

Cacti 1.2.16 - latest code branch 1.2.x

2020/12/09  08:35:03 - CMDPHP PHP ERROR WARNING Backtrace:   (/plugins/syslog/syslog_process.php[363]:file_get_contents(),  CactiErrorHandler())
2020/12/09 08:35:03 - ERROR PHP WARNING in  Plugin 'syslog':  file_get_contents(/var/www/html/cacti/plugins/syslog/syslog.css): failed  to open stream: No such file or directory in file:  /var/www/html/cacti/plugins/syslog/syslog_process.php  on line: 363

thanks a lot.

**Comment by TheWitness** [comment]
Yea, darn.  Thanks for reporting.

**Comment by TheWitness** [comment]
I've restored the syslog.css in the develop branch.
