### ISSUE TITLE
syslog_incoming logtime I see 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by itkroplis** [Cacti/plugin_syslog#147]
Hi!

I was updated my cacti server:
To Debian 10, apache2 latest, php7.3, syslog-ng 3 (3.19.1) , mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
I updated cacti to latest version. 
In cacti DB syslog_incoming logtime I see 0000-00-00 00:00:00  for any new row.

In WEBUI I see Unprocessed Messages info

How resolve it?

**Comment by TheWitness** [comment]
Double check your /etc/rsyslog.d/cacti.conf and ensure it's using the correct template.  The syslog templates changed a while ago.

**Comment by itkroplis** [comment]
/etc/rsyslog.d/cacti.conf ?! But I  use syslog-ng
nano /etc/syslog-ng/syslog-ng.conf


destination d_mysql {
sql(type(mysql)
host("localhost") username("user") password("passwordi")
database("syslog") table("syslog_incoming")
columns("facility_id", "priority_id", "program", "date", "time", "host", "message")
values("$FACILITY_NUM","$LEVEL_NUM","$PROGRAM","$YEAR-$MONTH-$DAY","$HOUR:$MIN:$SEC","$HOST","$MSGONLY"));
};

log {
source(s_all);
destination(d_mysql);
};

**Comment by itkroplis** [comment]
Ok I resolv it!
I change In syslog_incoming  Columns options to:
date and time values. And changed columns sequences.
![image](https://user-images.githubusercontent.com/29997706/103026974-b2dc7700-455d-11eb-91f9-8456645d1012.png)

**Comment by TheWitness** [comment]
Feel free to open a pull request on the README.md to update the instructions.

**Comment by itkroplis** [comment]
Ok, For versions comparing tests I install a fresh Ubuntu 20 server. But I don't find rsyslog configuration FAQ for cacti syslog plugin.
I make new DB syslog and restore it 
sudo mysql -u root -p syslog < /var/www/html/plugins/syslog/syslog.sql

I install apt install rsyslog-mysql
In  nano /etc/rsyslog.d/cacti.conf
add
$ModLoad imudp
$UDPServerRun 514
$ModLoad ommysql

$template cacti_syslog,"INSERT INTO syslog_incoming(facility_id, priority_id, program, logtime, host, message) \
  values (%syslogfacility%, %syslogpriority%, '%programname%', '%timegenerated:::date-mysql%', '%HOSTNAME%', TRIM('%msg%'))", SQL

*.* >localhost,syslog,cactiuser,cactiuser;cacti_syslog

In nano /etc/rsyslog.conf
uncommented
# provides UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# provides TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

I send syslogs msg from the remote host, I see it in tcpdump, but I don't see it in Syslog UI?

I think the configuration steps are missing. Any suggestions?

**Comment by itkroplis** [comment]
Ok, how is possible in syslog_incoming in "program" insert program name from rsyslog msg 
"commands.log  Dec 25 19:14:13 gitlab username: root [10393]: ifconfig [0]"  
I can't remember who handled it in the syslog-ng version. Currently I get all msg in "message" column.
On host used this rsyslog conf

cd /etc/rsyslog.d/
cat > commands.log.conf

$ModLoad imfile    #Load the imfile input module
$InputFilePollInterval 10
$InputFileName  /var/log/commands.log
$InputFileTag commands.log
$InputFileStateFile commands.log
$InputFileSeverity Info
$InputRunFileMonitor

$template commands_log, " commands.log  %msg% "

if $programname == 'commands.log' then @10.10.10.251:514;commands_log
if $programname == 'commands.log' then stop

**Comment by itkroplis** [comment]
I resolv it added in /etc/rsyslog.d/commands.log.conf    %hostname%
----------------------------------------------------------------------
$ModLoad imfile #Load the imfile input module
$InputFilePollInterval 10
$InputFileName /var/log/commands.log
$InputFileTag commands.log
$InputFileStateFile commands.log
$InputFileSeverity Info
$InputFileFacility local7
$InputRunFileMonitor

$template commands, " %hostname% commandlog %msg% "

if $programname == 'commands.log' then @10.10.10.46:514;commands
if $programname == 'commands.log' then stop
