### ISSUE TITLE
CMDPHP: ERROR: A DB Exec Failed!, Error:'126'

### ISSUE THREAD

**Issue by fadhilrajabian** [Cacti/plugin_syslog#148]
hello, this time I got an error like this in / var / log / syslog:
![image](https://user-images.githubusercontent.com/47592794/103208422-310c9500-4933-11eb-97e2-94a418f0f95a.png)

then no logs are logged into syslog.

![image](https://user-images.githubusercontent.com/47592794/103208495-5ac5bc00-4933-11eb-822c-8ab3397884ec.png)

I have tried to repair the syslog_incoming table.
but still can't.
I hope someone can help me

**Comment by TheWitness** [comment]
Sorry, we don't support that old version of syslog.  My recommendation is to update your Cacti.
