### ISSUE TITLE
Enhancement - popup window for long message

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_syslog#15]
Due to the fact that some messages are too long and they are cut I propose to add ability to view the message in popup Window.
![13](https://cloud.githubusercontent.com/assets/11805503/22756730/c61f38ec-ee50-11e6-90b7-d124a05338bb.png)

**Comment by cigamit** [comment]
Yea, we had that before, but it was taken out recently due to some performance issues.  The only way to do it right it through a callback.  I'll put it on the list.

**Comment by cigamit** [comment]
Okay, it's back.
