### ISSUE TITLE
installion on fedora isssue 1.2.17

### ISSUE THREAD

**Issue by ataullahsaleem** [Cacti/plugin_syslog#156]
*EXAMPLE:chown -R apache.apache /usr/share/cacti/log/

counot fix tmp/
Writable
/usr/share/cacti/log/
Not Writable

how to fix please help me out

**Comment by ataullahsaleem** [comment]
![image](https://user-images.githubusercontent.com/70479567/129070647-03ff35c9-06f2-498d-bfb8-54b73ac2f4ab.png)

**Comment by cigamit** [comment]
This is not a Cacti bug, but a user configuration issue.  The issues tracker is for tracking issues with Cacti, not a support forum. 
 Please ask about this instead on the Cacti Forums.  https://forums.cacti.net

**Comment by cigamit** [comment]
Just to note, you asked it on the repository for the Syslog Plugin also, which has nothing to do with your configuration issue.
