### ISSUE TITLE
syslog/database.php issues.

### ISSUE THREAD

**Issue by wonderzone** [Cacti/plugin_syslog#16]
Sorry, I'm not good at English and PHP...

in [syslog/database.php 2.0]

/* START CODE --------------------------------------------------------------- */
function syslog_db_replace($table_name, $array_items, $keyCols) {
       return db_replace($table_name, $array_items, $keyCols);
}

function syslog_sql_save($array_items, $table_name, $key_cols = 'id', $autoinc = true) {
       return sql_save($array_items, $table_name, $key_cols, $autoinc);
}
/* END CODE ----------------------------------------------------------------- */

For example, creating an alert rule with "$use_cacti_db = false;" setting will cause problems. Cacti will try to create record to Cacti-DB.
I changed it to...

/* START CODE --------------------------------------------------------------- */
function syslog_db_replace($table_name, $array_items, $keyCols) {
        global $syslog_cnn;
        return db_replace($table_name, $array_items, $keyCols, $syslog_cnn);
}

function syslog_sql_save($array_items, $table_name, $key_cols = 'id', $autoinc = true) {
        global $syslog_cnn;
        return sql_save($array_items, $table_name, $key_cols, $autoinc, $syslog_cnn);
}
/* END CODE ----------------------------------------------------------------- */

It looks like it was solved.
Thanks.

**Comment by cigamit** [comment]
Resolved, thanks!

**Comment by wonderzone** [comment]
Thanks for your response! ;-)
