### ISSUE TITLE
Message colum does not follow rfc

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_syslog#161]
The syslog rfc  5424 section 6. 1 allows for 2048 characters in the message part of the packet

The message colum is currently set to 1024

On rhel 8 some messages seem to go passed the 1024 limit

hmmm

 ommysql: db error (1406): Data too long for column 'message' at row 1

I've only seen this on rhel 8

**Comment by bmfmancini** [comment]
PR https://github.com/Cacti/plugin_syslog/pull/163

**Comment by netniV** [comment]
I'm sure you've seen our comments elsewhere but for the sake of repeating them here:

- Change to the develop branch
- Add a CHANGELOG entry
- Ensure upgrade code also modifies the column (otherwise there will be inconsistencies between current and new users)
