### ISSUE TITLE
Syslog - HTML Based Email Customization

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_syslog#167]
**Describe the solution you'd like**

We ask to have the possibility as for the "THOLD" plugin to have a minimum of control over the construction of the email in html format in order to change at least the bold and the colors of the alarm fonts.

**Additional context**
Example:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/1744639/156529090-3470f338-b159-4935-8f6d-292e210c6e6b.png">

thanks a lot.

**Comment by TheWitness** [comment]
This is resolved for the most port.  But I guess we should permit a subject in the Alert.

**Comment by anarkia1976** [comment]
Hi @TheWitness, thanks a lot.
