### ISSUE TITLE
syslog/syslog.sql issues.

### ISSUE THREAD

**Issue by wonderzone** [Cacti/plugin_syslog#17]
Sorry, I'm not good at English and PHP...

in [syslog/syslog_process.php 2.0] line: 213

/* CODE START ----------------------------------------------------------------*/
/* tally statistics for this interval */
if (read_config_option('syslog_statistics') == 'on') {
        syslog_db_execute('INSERT INTO `' . $syslogdb_default . '`.`syslog_statistics` (host_id, facility_id, priority_id, program_id, insert_time, records)
                SELECT host_id, facility_id, priority_id, program_id, NOW(), SUM(records) AS records
                FROM (SELECT host_id, facility_id, priority_id, program_id, COUNT(*) AS records
                        FROM syslog_incoming AS si
                        INNER JOIN syslog_hosts AS sh
                        ON sh.host=si.host
                        INNER JOIN syslog_programs AS sp
                        ON sp.program=si.program
                        WHERE status=' . $uniqueID . '
                        GROUP BY host_id, priority_id, facility_id, program_id) AS merge
                GROUP BY host_id, priority_id, facility_id, program_id');
/* CODE END ------------------------------------------------------------------*/

Table 'syslog_statistics' DDL..

  PRIMARY KEY (`host_id`,`facility_id`,`priority_id`,`insert_time`),

Problems will occur in case to...
`host_id`, `facility_id`, `priority_id`, `program_id`
`1`, `2`, `3`, `4`
`1`, `2`, `3`, `5`

`insert_time` is same if processed at the same time. Conflict with PRIMARY KEY constraints in case to Same `host_id`, `facility_id`, `priority_id` and `insert_time` and different `program_id`.

hmm...

I fixed it with BAD KNOWHOW..

I changed DDL...

-- CODE START ------------------------------------------------------------------
CREATE TABLE `syslog_statistics` (
  `host_id` int(10) unsigned NOT NULL,
  `facility_id` int(10) unsigned NOT NULL,
  `priority_id` int(10) unsigned NOT NULL,
--  `program_id` int(10) unsigned DEFAULT NULL,
  `program_id` int(10) unsigned NOT NULL DEFAULT 0,
  `insert_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `records` int(10) unsigned NOT NULL,
--  PRIMARY KEY (`host_id`,`facility_id`,`priority_id`,`insert_time`),
  PRIMARY KEY (`host_id`,`facility_id`,`priority_id`,`program_id`,`insert_time`),
  KEY `host_id` (`host_id`),
  KEY `facility_id` (`facility_id`),
  KEY `priority_id` (`priority_id`),
  KEY `program_id` (`program_id`),
  KEY `insert_time` (`insert_time`)
) ENGINE=InnoDB COMMENT='Maintains High Level Statistics';
-- CODE END --------------------------------------------------------------------

And I executed the following...

insert into syslog_programs (program) values ('UNKNOWN');
select program_id from syslog_programs where program='UNKNOWN'; -- check program_id
update syslog_programs set program_id=0 where program_id=<program_id of 'UNKNOWN'>;

hmm...bitter smile.
Thanks.

**Comment by cigamit** [comment]
Resolved, but not as you had expected.  You will have some work to do to normalize your schema.

**Comment by wonderzone** [comment]
Thank you very much for response!

However, a following error occurred.

\# mysql --version
mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for Linux (x86_64) using readline 6.3

\# mysql -u xxx -p syslog < syslog.sql
ERROR 1061 (42000) at line 238: Duplicate key name 'host_id'

hmm...Probably the reason is...

[syslog/syslog.sql 2.1]
247:   UNIQUE KEY (`host_id`,`facility_id`,`priority_id`,`program_id`,`insert_time`),
248:   KEY `host_id` (`host_id`),

An index named `host_id` is created on line 247, And duplicated key name on line 248. I commented out line 248 and succeeded.

Best regards!

**Comment by cigamit** [comment]
I've added names to the unique indexes in latest commit.

**Comment by wonderzone** [comment]
Thanks! Cacti_syslog working very well!
