### ISSUE TITLE
syslog_reports.php creates two duplicate records.

### ISSUE THREAD

**Issue by wonderzone** [Cacti/plugin_syslog#18]
Sorry again...

When create a new report, two duplicate records are created in the syslog_reports table. Probably because two \<form> tags are generated by `form_start()` and `draw_edit_form()`.
\</form> and corresponding \<javascript> are also duplicated by `form_save_button()` and `form_end()`, too.

[/cacti/plugins/syslog_reports.php]
415: form_start('syslog_reports.php');
416:
417: html_start_box($header_label, '100%', '', '3', 'center', '');
418:
419: draw_edit_form(
420:     array(
421:         'config' => array('form_name' => 'chk'),
422:         'fields' => inject_form_variables($fields_syslog_report_edit, (isset($report) ? $report : array()))
423:     )
424: );
425:
426: html_end_box();
427:
428: form_save_button('syslog_reports.php', '', 'id');
429:
430: form_end();

I using firefox 52.0.

Best Regards.

**Comment by cigamit** [comment]
Resolved, thanks for testing!
