### ISSUE TITLE
[SYSLOG] latest source - " report rules " tab - Internal server error

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_syslog#182]
If you click on "Report Rules" the action is failed with "500 internal server errror":
![image](https://user-images.githubusercontent.com/1744639/160842777-7f61a373-0eb0-42d3-b6da-484f7729a344.png)

thanks a lot

**Comment by TheWitness** [comment]
Thanks.  Fixed now.

**Comment by anarkia1976** [comment]
thanks a lot.
