### ISSUE TITLE
Invalid hosts

### ISSUE THREAD

**Issue by sosrobert** [Cacti/plugin_syslog#197]
Have a nice day!

We had a problem where the device name says invalid_host in syslog, especially for Raisecom switches. However, management sends its own host name as SNMP information. Thanks for help.

**Screenshots**
![cacti](https://user-images.githubusercontent.com/112083090/198527425-16f5e831-ee55-474a-acd8-99f464135ed4.png)

**Plugin (please complete the following information):**
 - Version: Syslog 4.0
 - Source: github

**Desktop (please complete the following information):**
- OS: Ubuntu 22.04.1 LTS
- Browser: Mozilla Firefox
- Version: Cacti 1.2.22

**Comment by TheWitness** [comment]
You have dns resolution enabled and the host does not have a good entry for the ip address in DNS.  Just add the hostname to Cacti's /etc/hosts or add the ip address to DNS or disable reverse host resolution.  This is not a bug.
