### ISSUE TITLE
Syslog severities are in the wrong order

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_syslog#203]
when setting a syslog alert to critical the sev is set to 2
but when you set a syslog alert to warning sev is set to 1

the severity levels should be  (based on itil)

Notice sev 0
Warning sev 2
Critical sev 1

**Comment by TheWitness** [comment]
Does this even matter?  It's just a number.

**Comment by bmfmancini** [comment]
It matters if your looking for that value when executing a script 
i.e usually critical would be sev 1 warning sev 2 and sev 0 is usually clear
