### ISSUE TITLE
Introduce ITIL based severity levels

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_syslog#204]
sev 1 – Critical Impact/System Down. Complete system outage.
    sev 2 – Significant Impact/Severe downgrade of services.
    sev 3 –Minor impact/Most of the system is functioning properly.
    sev 4 – Low Impact/Informational.
    sev 0 - Restored/Clear ( Not ITIL but used but most ticketing systems to clear a ticket)

**Comment by TheWitness** [comment]
It's more like a state than a level.  "Restored/Cleared" is not a severity, but a status.

**Comment by TheWitness** [comment]
Also, status is antithetical to syslog.  They are just events.  Status is upstream of the events.  I guess we kind of have that in a sense with the Syslog Priority already right?  Isn't priority really just another name for severity?

**Comment by bmfmancini** [comment]
Yes you are right on that I am going to close this one for now
