### ISSUE TITLE
Cacti 1.2.23 issue with syslog plugin 3.1

### ISSUE THREAD

**Issue by ataullahsaleem** [Cacti/plugin_syslog#207]
Dear Cacti Team ,

we have installed the cacti 1.2.23 version and using the 3.1 Syslog plugin /PHP8.1 
please help me how to fix the issue.

a log file has been attached 

![2023-01-27_16-49](https://user-images.githubusercontent.com/70479567/215306603-909b1d69-3890-45ae-93ca-c41ecc2b4650.png)

**Comment by TheWitness** [comment]
Update to the lastest develop version.  You will have to be on 1.2.23+ though.  You have an old database.php

**Comment by ataullahsaleem** [comment]
Dear Cacti 
share me develop cacti link please

**Comment by TheWitness** [comment]
Well, from Linux, it's simple.

```sh
git clone https://github.com/cacti/plugin_syslog.git
```
