### ISSUE TITLE
Syslog Device Filter

### ISSUE THREAD

**Issue by Bochi75** [Cacti/plugin_syslog#209]
**Describe the bug**
Hello Team,
I just installed last version of Syslog and I'm not able to filter on devices on Syslog Message Filter section.
Someone can help please.
Regards,

**To Reproduce**
1. Go to 'Syslog TAB'
2. Click on 'Device..'
4. No host available to select

**Expected behavior**
Filter to specific device on syslog.

**Plugin (please complete the following information):**
 - Version: 4.1
 - Source: github

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Browser Brave/Firefox/Chrome

<img width="140" alt="Syslog" src="https://user-images.githubusercontent.com/114311163/221875330-74ed6d90-b78d-4ec9-a4ad-e2226c8173b6.png">

**Comment by TheWitness** [comment]
This would normally mean that you have no incoming records or no records have been processed.  It goes away once the plugin is properly setup.

**Comment by TheWitness** [comment]
Nothing to fix here.
