### ISSUE TITLE
Error: Please rename your config.php.dist file in the syslog directory, and change setup your database before installing.

### ISSUE THREAD

**Issue by denispolicarpocampos** [Cacti/plugin_syslog#21]
I am installing syslog on cacti, but when I click the plugin install button it will display an error message: "Error: change the config.php.dist file in the syslog directory and change the database configuration before installing."

I went to config.php.dist and changed the syslogdb_password, the rest left default. I do not know what I have and how I have to change the database

I still have the same problem when I click Install Install.

Can someone help me?

**Comment by wonderzone** [comment]
Let's rename your 'config.php.dist' to 'config.php', and retry again! : )

```
# mv /path/to/cacti/plugins/syslog/config.php.dist /path/to/cacti/plugins/syslog/config.php
```
......or......
```
# cp /path/to/cacti/plugins/syslog/config.php.dist /path/to/cacti/plugins/syslog/config.php
```

**Comment by denispolicarpocampos** [comment]
I renamed it and got it installed. Now the syslog top bar appears, but no log appears. Do I have to configure anything else?

Thank you!

**Comment by cigamit** [comment]
Yes, you need to configure your server to log messages to syslog (and/or accept syslog messages from other servers).  There are plenty of topics on this on the forums.  This is not a bug in syslog, so please use the forums for support on getting your server properly configured.
