### ISSUE TITLE
Device Filter missing devices

### ISSUE THREAD

**Issue by RioLia** [Cacti/plugin_syslog#211]
Version:
Windows server 2019/Cacti1.2.23/syslog4.1

When using Device Filter, some devices are missing，and the hostname including the IP address is not displayed completely.

![1687651996261](https://github.com/Cacti/plugin_syslog/assets/137277848/e63795e6-58f3-43c9-bcb4-45918208d67a)

![image](https://github.com/Cacti/plugin_syslog/assets/137277848/3557835a-70f3-4c37-a96f-8b5b102fc795)

eg: host "QMLD-9306" is missing in the filter, and host "A-4-172.19.1.90" is displayed as "A-4-172"。but they have No problem in SQL.

**Comment by TheWitness** [comment]
Yea, this is a bug in the IP address detection logic. It thinks it's a domain and is stripping it.

**Comment by TheWitness** [comment]
Should be fixed now in the develop branch.  If so, you can close.

**Comment by RioLia** [comment]
After installing the develop branch. The problem has been solved, thank you very much.
