### ISSUE TITLE
Is it possible to increase the display quantity of the device filter?

### ISSUE THREAD

**Issue by RioLia** [Cacti/plugin_syslog#212]
The device filter can display a maximum of 30 hosts, and the excess part will be sorted by host name and displayed in the top 30.
Hosts with more than 30 in the sorting will not be able to be filtered and displayed by device filter.
and the program filter also has an upper limit.I don't know if there is this BUG too.

**Comment by TheWitness** [comment]
There is a setting for this under `Console > Configuration > Settings > Visual > Auto Complete Rows`
