### ISSUE TITLE
Documentation correction for rsyslogd config for version above 2.4

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_syslog#216]
In the README.md the section explaining how to configure the /etc/rsyslog.d/cacti.conf

The same is indicated for rsyslog below 2.0
`
console
$ModLoad imudp
$UDPServerRun 514
$ModLoad ommysql

$template cacti_syslog,"INSERT INTO syslog_incoming(facility_id, priority_id, program, logtime, host, message) \
  values (%syslogfacility%, %syslogpriority%, '%programname%', '%timegenerated:::date-mysql%', '%HOSTNAME%', TRIM('%msg%'))", SQL

*.* >localhost,my_database,my_user,my_password;cacti_syslog
`

For the version 2.4 and above it should be:
`
module(load="ommysql")
action(type="ommysql" server="localhost" serverport="3306"
       db="syslogDB" uid="userID" pwd="passwdID")

$template cacti_syslog,"INSERT INTO syslog_incoming(facility_id, priority_id, program, logtime, host, message) \
  values (%syslogfacility%, %syslogpriority%, '%programname%', '%timegenerated:::date-mysql%', '%HOSTNAME%', TRIM('%msg%'))", SQL
`

**Comment by TheWitness** [comment]
This is resolved.
