### ISSUE TITLE
ERROR PHP DEPRECATED on php 8.2

### ISSUE THREAD

**Issue by arno-st** [Cacti/plugin_syslog#222]
Hello,
I have a issue on syslog tab, when I go to the tab 'Alert Logs' I got tons of this error on my cacti.log
I think it has to do with some filter I have (look my 2 other posts about that).
Is there a way to correct this ?
I'musing cacti 1.2.26 (develop branch of last 12 januarry) and syslog develop of januarry 5
```
16/01/2024`  13:42:54 - CMDPHP PHP ERROR Backtrace:   (/plugins/syslog/syslog.php[106]:syslog_messages(),  /plugins/syslog/syslog.php[1920]:CactiErrorHandler())
--
16/01/2024 13:42:54 - ERROR PHP DEPRECATED in  Plugin 'syslog':  strlen(): Passing null to parameter #1 ($string) of type string is  deprecated in file: /usr/share/cacti/plugins/syslog/syslog.php  on line:  1920
```

**Comment by TheWitness** [comment]
Should be fixed now.

**Comment by arno-st** [comment]
I't seams ok, I don't have any error anymore.
