### ISSUE TITLE
Syslog for Windows Server 2022

### ISSUE THREAD

**Issue by sosrobert** [Cacti/plugin_syslog#225]
**Describe the bug**

Hello!

We installed Cacti on a Windows server, so far everything has been fine. We want to install the syslog plugin now and our problem is that we don't know how to install it because we couldn't find an installation guide. We installed the plugin and got stuck with Rsyslog. I would like to ask for your help in this!

Thank you very much for your answer!

**Plugin:**
 - Version: Syslog 4.1
 - Source: github

**Desktop:**
 - OS: Windows Server 2022
 - Browser: Google Chrome 121.0.6167.140
 - Cacti version: 1.2.26

**Comment by sosrobert** [comment]
Can I get some feedback? Thank you very much!

**Comment by sosrobert** [comment]
Can I get some feedback? Thank you very much!

**Comment by xmacan** [comment]
for support please use https://forums.cacti.net

**Comment by TheWitness** [comment]
You can always forward to a Linux server and have it insert into Cacti.
