### ISSUE TITLE
In version 4.2, messages cannot be displayed completely

### ISSUE THREAD

**Issue by linqianye** [Cacti/plugin_syslog#226]
**Describe the bug**
After upgrading to v4.2, the detailed log messages in the table are not fully displayed in the new version.

**Screenshots**

**Version:**
 - Cacti: v1.2.27
 - syslog: v4.2

**Comment by linqianye** [comment]
![image_20240613111010](https://github.com/Cacti/plugin_syslog/assets/39152144/f2b6d591-e1bf-4a44-866a-c890a1d4451e)
![image_20240613110932](https://github.com/Cacti/plugin_syslog/assets/39152144/4f4b4bf8-9e7a-4d78-a497-726d9f45214d)

**Comment by jdcoats** [comment]
see the "trim" filter? change that to 300
