### ISSUE TITLE
No design for detailed viewing Alert Logs

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_syslog#23]
When I open the detailed view of event Alert Logs, drawn table without design.
![46](https://cloud.githubusercontent.com/assets/11805503/25374490/4f4b4864-29a6-11e7-8a7c-d653298363c8.png)

**Comment by cigamit** [comment]
That output is horrible.

**Comment by cigamit** [comment]
Should be fixed.  Thanks for reporting.
