### ISSUE TITLE
syslog 2.1 compatible with cacti 0.8.8h

### ISSUE THREAD

**Issue by rchen29** [Cacti/plugin_syslog#26]
Hey Guys,

I'm trying to replace syslog 2.1 with our old 1.22. 
Here were what I did:
1. Disable old plugin.
2. Uninstall old plugin.
3. Remove old syslog folder.
4. Rename and move new syslog folder to plugins.
5. Go to cacti PIA, and trying to install new plugin. (issue happened)
Then, my PIA manager won't show anything. Even the plugins I have installed. When I remove syslog folder, it back to normal. Any idea?

**Comment by cigamit** [comment]
The new plugins are only compatible with 1.X branch.  They will not be made backwards compatible with the 0.8.8 branch.

**Comment by rchen29** [comment]
The syslog report(v1.22) is not working with cacti 0.8.8h. Is there anyway we can fix it?

**Comment by cigamit** [comment]
Yea, learn PHP.  Better upgrade to Cacti 1.x
