### ISSUE TITLE
Syslog Plugin Installed but not showing up anywhere

### ISSUE THREAD

**Issue by esc15** [Cacti/plugin_syslog#27]
I installed the Syslog plugin, enabled it in Plugin Management, and verified plugin permissions were set. I just do not see where to access it. This is a fairly new installation of Cacti on Centos using yum. The syslog_incoming table is being populated when I look at the database. I tried browsing to plugins/syslog/syslog.php, but it just shows a couple of tabs (System Logs and Alert Logs) without any data.

/var/log/cacti/cacti.log does not show any errors.

/var/log/httpd/ssl_error_log shows the following when I browse to plugins/syslog/syslog.php.
[Wed May 17 14:13:23.721518 2017] [:error] [pid 5820] [client x.x.x.x:50549] PHP Fatal error:  Call to undefined function syslog_db_fetch_assoc() in /usr/share/cacti/plugins/syslog/syslog.php on line 823

Any advise is welcome.

**Comment by cigamit** [comment]
What Cacti version?  Did you actually 'enable' the plugin?

**Comment by cigamit** [comment]
I think that this is a support issue and not a bug.

**Comment by hackdefendr** [comment]
Need to re-open this bug please. 

I just installed the current development version of this plugin on Cacti v1.1.6 and there is no top tab created for the plugin. Only place I see is under settings.

**Comment by smiles1969** [comment]
The top tab will not appear unless you enable plugin permissions for syslog under the user you are logged in as.
