### ISSUE TITLE
Plugin hooks?

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_syslog#3]
Cacti log getting spammed with these:

05/17/2016 04:50:02 PM - CMDPHP SQL Backtrace: (/poller_reports.php: 71 include_once)(/include/global.php: 261 include_once)(/include/global_arrays.php: 1383 api_plugin_hook)(/lib/plugins.php: 70 syslog_config_arrays)(/plugins/syslog/setup.php: 915 db_fetch_cell)(/lib/database.php: 175 db_fetch_cell_prepared)(/lib/database.php: 220 cacti_debug_backtrace)
05/17/2016 04:50:02 PM - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 80 include)(/include/global.php: 261 include_once)(/include/global_arrays.php: 1383 api_plugin_hook)(/lib/plugins.php: 70 syslog_config_arrays)(/plugins/syslog/setup.php: 915 db_fetch_cell)(/lib/database.php: 175 db_fetch_cell_prepared)(/lib/database.php: 220 cacti_debug_backtrace)
05/17/2016 04:50:02 PM - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 80 include)(/include/global.php: 261 include_once)(/include/global_arrays.php: 1383 api_plugin_hook)(/lib/plugins.php: 70 syslog_config_arrays)(/plugins/syslog/setup.php: 914 db_fetch_cell)(/lib/database.php: 175 db_fetch_cell_prepared)(/lib/database.php: 220 cacti_debug_backtrace)
05/17/2016 04:50:02 PM - CMDPHP SQL Backtrace: (/poller_reports.php: 71 include_once)(/include/global.php: 261 include_once)(/include/global_arrays.php: 1383 api_plugin_hook)(/lib/plugins.php: 70 syslog_config_arrays)(/plugins/syslog/setup.php: 914 db_fetch_cell)(/lib/database.php: 175 db_fetch_cell_prepared)(/lib/database.php: 220 cacti_debug_backtrace)
05/17/2016 04:50:02 PM - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 80 include)(/include/global.php: 261 include_once)(/include/global_arrays.php: 1383 api_plugin_hook)(/lib/plugins.php: 70 syslog_config_arrays)(/plugins/syslog/setup.php: 915 db_fetch_cell)(/lib/database.php: 175 db_fetch_cell_prepared)(/lib/database.php: 220 cacti_debug_backtrace)

**Comment by cigamit** [comment]
make sure you undo your changes in setup.php.  I have no idea what this is about.  your line numbers in plugins/syslog/setup.php do not align with github.

**Comment by smiles1969** [comment]
Ok I removed that code, do these line up?

05/18/2016 10:50:03 AM - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 80 include)(/include/global.php: 261 include_once)(/include/global_arrays.php: 1383 api_plugin_hook)(/lib/plugins.php: 70 syslog_config_arrays)(/plugins/syslog/setup.php: 910 db_fetch_cell)(/lib/database.php: 175 db_fetch_cell_prepared)(/lib/database.php: 220 cacti_debug_backtrace)
05/18/2016 10:50:03 AM - CMDPHP SQL Backtrace: (/poller_maintenance.php: 39 include)(/include/global.php: 261 include_once)(/include/global_arrays.php: 1383 api_plugin_hook)(/lib/plugins.php: 70 syslog_config_arrays)(/plugins/syslog/setup.php: 910 db_fetch_cell)(/lib/database.php: 175 db_fetch_cell_prepared)(/lib/database.php: 220 cacti_debug_backtrace)

**Comment by cigamit** [comment]
just curious, what version of MySQL are you using, and is syslog on the same server or on another?  Is it in the Cacti database or another?

**Comment by cigamit** [comment]
okay, I see the issue now.  will get it fixed shortly.

**Comment by cigamit** [comment]
should be fixed in the latest commit.

**Comment by smiles1969** [comment]
error messages are gone after git pull. 

Thanks :)
