### ISSUE TITLE
cacti 1.1.10 syslog 1.21 how export record to csv?

### ISSUE THREAD

**Issue by itkroplis** [Cacti/plugin_syslog#32]
Hi!

cacti 1.1.10 syslog 1.21 how export record to csv?
I press button "Export" but nothing happens :(

**Comment by cigamit** [comment]
Resolved, thanks for reporting!

**Comment by itkroplis** [comment]
Yes, this is resolved, but after last file change, "All Programs" not work well. I press, but not show jumping menu for Programs list :(

**Comment by cigamit** [comment]
What cacti version?

**Comment by cigamit** [comment]
Sorry, move to the 1.1.12 or 1.1.13.

**Comment by cigamit** [comment]
Note that this programs dropdown is now a autocomplete callback in order to speed the UI.

**Comment by itkroplis** [comment]
It is bad. I can not select the I needed "Application".  I use in syslog only .log files from remote servers. And select them, after "Application" 
Now it's time to delete text from Application, so that could to choose necessary Application.

**Comment by itkroplis** [comment]
It is bad. When "Programs" is more than 20, can not choose all.

I change in syslog.php LIMIT 50

$programs = syslog_db_fetch_assoc("SELECT program_id, program FROM syslog_programs $sql_where ORDER BY program LIMIT 50");
