### ISSUE TITLE
Syslog 2.1 - Doesn't show any register

### ISSUE THREAD

**Issue by rsanchezre** [Cacti/plugin_syslog#36]
Hi,
I'm running cacti 1.1.6 and syslog plugin 2.1. When i try to see some syslog register (Syslog tab - System logs), it doesn't show me any of them.  But, i added alert roules and when i go to Alert Logs tab, registers are shown me correctly

I made the following,
- I've check that the syslog plugin was installed correctly.
- I've set up the config.php correcty.
- I've checked that syslog messages are comming from devices and they are inserted into syslog_incomming table of MySQL.
- I've checked that syslog_host table is filling up.
- I've not have error messages in cacti logs.

So, I'd apprecite if you could tell me what can i see to resolve my issue
Regards.
Rodrigo

**Comment by cigamit** [comment]
This is a support issue and should be handled through the forums.  We don't address support issues here.  Bugs only.
