### ISSUE TITLE
Cannot enable Syslog

### ISSUE THREAD

**Issue by hgortega** [Cacti/plugin_syslog#37]
Hi, I installed syslog plugin in my cacti machine, but I cannot enable it. I have the next error:
ERROR PHP ERROR in Plugin 'syslog': Call to undefined function get_current_page() in file: /usr/share/cacti/plugins/syslog/setup.php on line: 188 
Can you help me, I did not use this plugin before.
I am using cacti v 1.1.2 on Centos 7
syslog v 2.1
Thanks

**Comment by cigamit** [comment]
Resolved.  Cacti needs to be more recent where we introduced the get_current_page() function.
