### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Cramin** [Cacti/plugin_syslog#38]
Please add info about renaming file config.php.dist to config.php in ~/plugins/syslog directory. Without that you cannot install plugin in web interface.

**Comment by jpobeda** [comment]
I'd also add that you need to install rsyslog-mysql, for CentOS at least. 

EDIT: actually I realized it's on https://docs.cacti.net/plugin:syslog.config

**Comment by cigamit** [comment]
Resolved.  Thanks!
