### ISSUE TITLE
Message contains quotes

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_syslog#4]
When a syslog message contains quotes as part of the message, they are not being escaped/sanitized and results in an SQL error for example:

05/19/2016 12:20:02 PM - CMDPHP ERROR: A DB Exec Failed!, Error:1064, SQL:"INSERT INTO `cacti`.`syslog_logs` (`seq`, `alert_id`, `logseq`, `logtime`, `logmsg`, `host`, `facility_id`, `priority_id`, `count`, `html`) VALUES ("", "2", "2456", "2016-05-19 12:19:26", "Event for ONT "serial #: 49143, vendor: CXNK" at 2016/05/19 12:19:24.95: "ONT Event: Departure -- GPON port "1/2""", "lab_e7_2", "16", "6", "1", "<html><head><style type='text/css'>.body { font-size:12pt\; font-family:Verdana,Arial,Helvetica,sans-serif\;}.table { align:center\; width:100%\;}.table tr th.th { background: rgba(138,179,105,1)\; background: -moz-linear-gradient(top, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%)\; background: -webkit-gradient(left top, left bottom, color-stop(0%, rgba(138,179,105,1)), color-stop(100%, rgba(63,117,15,1)))\; background: -webkit-linear-gradient(top, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%)\; background: -o-linear-gradient(top, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%)\; background: -ms-linear-gradient(top, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%)\; background: linear-gradient(to bottom, rgba(138,179,105,1) 0%, rgba(63,117,15,1) 100%)\; filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#8ab369', endColorstr='#3f750f', GradientType=0 )\;}.th { color: snow\; font-weight:bold\; vertical-align:bottom\; text-align:left\;}.td { color:black\; font-family:Verdana,Arial,Helvetica,sans-serif\; text-align:left\;}.h1 { text-align:center\; font-family:Verdana,Arial,Helvetica,sans-serif\; font-size:16pt\;}.p { text-align:left\; font-family:Verdana,Arial,Helvetica,sans-serif\; font-size:12pt\;}</style></head><body class='body'><h1 class='h1'>Cacti Syslog Plugin Alert 'E7 ONT Departure'</h1><table class='table' cellspacing='0' cellpadding='3' border='1'><tr><th class='th'>Hostname</th><th class='th'>Date</th><th class='th'>Severity</th><th class='th'>Priotity</th><th class='th'>Message</th></tr><tr><td class='td'>lab_e7_2</td><td class='td'>2016-05-19 12:19:26</td><td class='td'>Warning</td><td class='td'></td><td class='td'>Event for ONT "serial #: 49143, vendor: CXNK" at 2016/05/19 12:19:24.95: "ONT Event: Departure -- GPON port "1/2""</td></tr></table></body></html>") ON DUPLICATE KEY UPDATE `alert_id`=VALUES(`alert_id`), `logseq`=VALUES(`logseq`), `logtime`=VALUES(`logtime`), `logmsg`=VALUES(`logmsg`), `host`=VALUES(`host`), `facility_id`=VALUES(`facility_id`), `priority_id`=VALUES(`priority_id`), `count`=VALUES(`count`), `html`=VALUES(`html`)'

Original syslog message:

May 19 12:19:26 lab_e7_2 : Event for ONT "serial #: 49143, vendor: CXNK" at 2016/05/19 12:19:24.95: "ONT Event: Departure -- GPON port "1/2""

It also causes issues with any resulting alert email message as the message breaks the HTML as well.

**Comment by cigamit** [comment]
just did a commit. please verify

**Comment by smiles1969** [comment]
It appears this issue is resolved, 

However it appears there are more fields (program for example) and tables in the database than the syslog.sql file is defining, so I'm not getting messages transferred to syslog table.

**Comment by cigamit** [comment]
you should have the tables setup by the GUI and not use the sql schema.  however, if your syslog server is not the cacti server, this can be more confusing.  so, the schema has been updated just now.

**Comment by smiles1969** [comment]
I believe I did run the GUI setup, and had the table issues. After running the new .sql file the schema is correct now and everything appears to be functional.

Thank you!
