### ISSUE TITLE
Alert rule : Passing parameters to Alert Command

### ISSUE THREAD

**Issue by andersonreloaded** [Cacti/plugin_syslog#43]
Hello Folks,
Configured Syslog alert rule which checks if syslog message matches the string "SYS-5-CONFIG_I" and a PHP script is run, which is defined in the Alert Command section as shown below:
`-c 'php /nms/cacti/scripts/cisco_config_backup.php <HOSTNAME> <MESSAGE>'`

To extract the user field who has changed the configuration, complete syslog message needs to be passed using <MESSAGE>. But for some reason the script is reading only initial words or truncated portion of the <MESSAGE>. 

Any ideas how to fix the issue.

**Comment by jpobeda** [comment]
@andersonreloaded so you're basically seing that the script you made is failing to run?

Hard to tell without looking at the script. You're looking for getting what? an email saying this user has changed and saved the config on this device sort of thing?

**Comment by netniV** [comment]
Try putting the `<HOSTNAME>` and `<MESSAGE>` into double quotes and see if the full message comes through then.

**Comment by andersonreloaded** [comment]
@netniV Thanks! It worked. 

However, I see Syslog messages from Cisco boxes have double spaces for single digit dates. As an intermediate fix, used PHP function to replace double or more spaces with single space using
 `preg_replace( '/\s\s+/', ' ', $a['message'] )`  in the `function alert_replace_variables` of `syslog_process.php` file, where the parameters are passed to external script.

Any better ideas ?

**Comment by andersonreloaded** [comment]
@jpobeda The aim is to take configuration backup when user modifies it. The backup script is executed through Syslog alert, to which `<HOSTNAME>` and `<MESSAGE>` fields are supplied as additional arguments. Since the `<MESSAGE>` field comprises of multiple words ( including user name) separated by single and/or double spaces, using single quotes to pass the argument lead to truncation at first single space. Using double quotes as suggested by @netniV seems to work. However, presence of double or multiple spaces need to be addressed.

**Comment by netniV** [comment]
That is a message thing and nothing something that plugin_syslog should be modifying.  I would suggest passing it to an interim script that would remove them if you are currently using a compiled program at the moment.  Pretty much doing the same as the preg_replace above.

**Comment by andersonreloaded** [comment]
@netniV 
I agree with you. My fix is just a temporary one. Shall attempt to resolve it outside plugin_syslog.

**Comment by cigamit** [comment]
I'm going to start using cacti_escapeshellarg() for escaping the replacements.

**Comment by andersonreloaded** [comment]
@cigamit Thank you for the fix.
