### ISSUE TITLE
No logs showing from Ubiquiti Edgeswitch

### ISSUE THREAD

**Issue by glwallum** [Cacti/plugin_syslog#45]
Installed and configured, no logs populating from Ubiquiti Edgeswitch devices.

Tested environment with Cisco devices (syslogs show)
Tested with wireshark to show logs were being sent correctly to server

Below is wireshark capture of the log.

5 26.326881061 172.16.0.11 → 172.16.0.6 Syslog 194 USER.NOTICE: Jan 22 04:52:53 devicename TRAPMGR[trapTask]: traputil.c(735) 43784 %% Session 0 of type 3 ended for user username connected from 172.16.0.8.\000

**Comment by netniV** [comment]
Do you see anything in the syslog_incoming table?  If not, check that your syslog daemon configuration is correctly setup to put it into the table.

**Comment by glwallum** [comment]
Yes they are appearing in the syslog_incoming table.Below are two examples,
the first is the cisco switch that is generating syslogs and the other is
the Ubiquiti which are not. I tested another syslog program and the
Ubiquiti messages were coming through as normal. Please let me know of any
solutions it would be greatly appreciated

|          23 |           4 | %CDP-W-NATIVE_VLAN_MISMATCH | 2018-04-24 |
13:07:3
                    0 | 172.16.0.16       | Native VLAN mismatch detected
on interface gi2.

                        | 249371 |      0 |


|           1 |           6 | DNS_CLI                     | 2018-09-02 |
03:01:2
                    2 | C1S2EdgeSwitch-1  | dns_client_txrx.c(711) 995301
%% DNS Client: Failed to s
                                      end query packet. Can't reach DNS
server at 255.255.255.255. | 249372 |      0 |

**Comment by glwallum** [comment]
I have found the issue, the NTP server is giving false times. Please close
