### ISSUE TITLE
Cacti 1.2.0 Latest - Syslog Latest - Loading image error

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_syslog#47]
Hi,

after the latest update i have see these error into the browser console related to loading of these buttons images:
![image](https://user-images.githubusercontent.com/1744639/39804779-4da197da-5375-11e8-9b32-830f28ab0cde.png)
Browser Log:
add.png:1 GET https://x.x.x.x:1543/cacti/images/add.png 404 (Not Found)
delete.png:1 GET https://x.x.x.x:1543/cacti/images/delete.png 404 (Not Found)

When i make a second refresh all is ok:
![image](https://user-images.githubusercontent.com/1744639/39804877-92a41d30-5375-11e8-8370-984d6552310b.png)

thanks a lot

**Comment by netniV** [comment]
Can you confirm the full image URL on the both attempts?

**Comment by anarkia1976** [comment]
yes.
ls -lrt /usr/share/cacti/plugins/syslog/images/add.png
-rwxrwxr-x 1 apache apache 733 Apr  4 10:56 /usr/share/cacti/plugins/syslog/images/add.png
ls -lrt /usr/share/cacti/plugins/syslog/images/delete.png
-rwxrwxr-x 1 apache apache 715 Apr  4 10:56 /usr/share/cacti/plugins/syslog/images/delete.png

**Comment by netniV** [comment]
I meant on the browser side :)

**Comment by netniV** [comment]
Before when broken and after when working.

**Comment by anarkia1976** [comment]
Path to Images are always reacheable.
The problem is present only the first time you start the browser and go to syslog plugins. If you close only cacti tab without close the browser images aren't broken.

**Comment by pautiina** [comment]
Hello. I also have this Issue

**Comment by netniV** [comment]
OK, I couldn't see the issue last time, but I see it today.  The path is missing the plugins/syslog/ portition

**Comment by netniV** [comment]
This has now been resolved.
