### ISSUE TITLE
Cacti 1.2.0 Latest - Syslog Latest - Search Error

### ISSUE THREAD

**Issue by anarkia1976** [Cacti/plugin_syslog#48]
Hi,
search filter for syslog statistics didn't work:

2018/05/16  16:10:37 - CMDPHP SQL Backtrace: (/plugins/syslog/syslog.php: 96  syslog_statistics)(/plugins/syslog/syslog.php: 263  syslog_db_fetch_cell)(/plugins/syslog/database.php: 72  db_fetch_cell)(/lib/database.php: 245  db_fetch_cell_prepared)(/lib/database.php: 292 cacti_debug_backtrace)
2018/05/16 16:10:37 - CMDPHP SQL Backtrace:  (/plugins/syslog/syslog.php: 96  syslog_statistics)(/plugins/syslog/syslog.php: 248  get_stats_records)(/plugins/syslog/syslog.php: 389  syslog_db_fetch_assoc)(/plugins/syslog/database.php: 101  db_fetch_assoc)(/lib/database.php: 372  db_fetch_assoc_prepared)(/lib/database.php: 413 cacti_debug_backtrace)
2018/05/16 16:10:37 - DBCALL ERROR: SQL Assoc Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near 'GROUP BY  sh.host, sh.host, sf.facility, sp.priority, spr.program, UNIX_TIMESTAMP'  at line 1
2018/05/16 16:10:37 - DBCALL ERROR: SQL Assoc Failed!, Error:1064,  SQL:'SELECT sh.host, sf.facility, sp.priority, spr.program,  sum(ss.records) AS records,  FROM_UNIXTIME(TRUNCATE(UNIX_TIMESTAMP(insert_time)/300,0)*300) AS  insert_time FROM `cacti`.`syslog_statistics` AS ss LEFT JOIN  `cacti`.`syslog_facilities` AS sf ON ss.facility_id=sf.facility_id LEFT  JOIN `cacti`.`syslog_priorities` AS sp ON ss.priority_id=sp.priority_id  LEFT JOIN `cacti`.`syslog_programs` AS spr ON  ss.program_id=spr.program_id LEFT JOIN `cacti`.`syslog_hosts` AS sh ON  ss.host_id=sh.host_id WHERE ss.program_id= GROUP BY sh.host, sh.host,  sf.facility, sp.priority, spr.program, UNIX_TIMESTAMP(insert_time) DIV  300 ORDER BY `host` ASC LIMIT 0,100'
2018/05/16 16:10:37 - CMDPHP Input Validation Not Performed for  'program' Backtrace: (/plugins/syslog/syslog.php: 96  syslog_statistics)(/plugins/syslog/syslog.php: 248  get_stats_records)(/plugins/syslog/syslog.php: 354  get_request_var)(/lib/html_utility.php: 328  html_log_input_error)(/lib/html_validate.php: 44 cacti_debug_backtrace)
2018/05/16 16:10:34 - CMDPHP SQL Backtrace:  (/plugins/syslog/syslog.php: 96  syslog_statistics)(/plugins/syslog/syslog.php: 263  syslog_db_fetch_cell)(/plugins/syslog/database.php: 72  db_fetch_cell)(/lib/database.php: 245  db_fetch_cell_prepared)(/lib/database.php: 292 cacti_debug_backtrace)
2018/05/16 16:10:34 - CMDPHP SQL Backtrace:  (/plugins/syslog/syslog.php: 96  syslog_statistics)(/plugins/syslog/syslog.php: 248  get_stats_records)(/plugins/syslog/syslog.php: 389  syslog_db_fetch_assoc)(/plugins/syslog/database.php: 101  db_fetch_assoc)(/lib/database.php: 372  db_fetch_assoc_prepared)(/lib/database.php: 413 cacti_debug_backtrace)
2018/05/16 16:10:34 - DBCALL ERROR: SQL Assoc Failed!, Error: You  have an error in your SQL syntax; check the manual that corresponds to  your MariaDB server version for the right syntax to use near 'GROUP BY  sh.host, sh.host, sf.facility, sp.priority, spr.program, UNIX_TIMESTAMP'  at line 1
2018/05/16 16:10:34 - DBCALL ERROR: SQL Assoc Failed!, Error:1064,  SQL:'SELECT sh.host, sf.facility, sp.priority, spr.program,  sum(ss.records) AS records,  FROM_UNIXTIME(TRUNCATE(UNIX_TIMESTAMP(insert_time)/300,0)*300) AS  insert_time FROM `cacti`.`syslog_statistics` AS ss LEFT JOIN  `cacti`.`syslog_facilities` AS sf ON ss.facility_id=sf.facility_id LEFT  JOIN `cacti`.`syslog_priorities` AS sp ON ss.priority_id=sp.priority_id  LEFT JOIN `cacti`.`syslog_programs` AS spr ON  ss.program_id=spr.program_id LEFT JOIN `cacti`.`syslog_hosts` AS sh ON  ss.host_id=sh.host_id WHERE ss.host_id=245 AND ss.program_id= GROUP BY  sh.host, sh.host, sf.facility, sp.priority, spr.program,  UNIX_TIMESTAMP(insert_time) DIV 300 ORDER BY `host` ASC LIMIT 0,100'
2018/05/16 16:10:34 - CMDPHP Input Validation Not Performed for  'program' Backtrace: (/plugins/syslog/syslog.php: 96  syslog_statistics)(/plugins/syslog/syslog.php: 248  get_stats_records)(/plugins/syslog/syslog.php: 354  get_request_var)(/lib/html_utility.php: 328  html_log_input_error)(/lib/html_validate.php: 44 cacti_debug_backtrace)

thanks

**Comment by cigamit** [comment]
@anarkia1976, this is resolved now.
