### ISSUE TITLE
syslog 2.1 email template not formatted correctly

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_syslog#50]
I will attach the old email and the new email
![screen shot 08-17-18 at 03 57 pm 001](https://user-images.githubusercontent.com/42470924/44286376-6b8ca000-a258-11e8-89ee-53558cc2be18.PNG)
![screen shot 08-17-18 at 03 57 pm](https://user-images.githubusercontent.com/42470924/44286378-6c253680-a258-11e8-878a-a88b3b7e7091.PNG)

**Comment by netniV** [comment]
The both could use some loving but I agree the former looks better.  Do you know what version you had before that produced that?

**Comment by jdcoats** [comment]
1.3

**Comment by jdcoats** [comment]
This may be a false report also. I just noticed that when these messages come to my phone they are correct. Maybe the code works with mobile viewer and not standard outlook, but thenproblem did come up immediately post upgrade. 
![4254bafd-80f1-44ed-95f0-7cfff6a0623d](https://user-images.githubusercontent.com/42470924/44295251-55d8a400-a273-11e8-8e07-9dff1979de3f.png)

**Comment by jdcoats** [comment]
Mobile device mail viewer shows the outline and color but not dividing grid. o365 web mail viewer shows the grid but no color. Outlook 2016 doesn't show the color or the grid.

**Comment by cigamit** [comment]
Email client piss me off.

**Comment by cigamit** [comment]
Going to close this one.  I'm thinking about using formats moving forward.  Will log that separately.
