### ISSUE TITLE
Duplicated partition named when reorganizing

### ISSUE THREAD

**Issue by jpobeda** [Cacti/plugin_syslog#51]
Following [discussion ](https://forums.cacti.net/viewtopic.php?f=14&t=58889&p=274128#p274128) on forum.

DB is separated from Cacti BUT on the same host.

Settings at the time it happened

![syslog_bug](https://user-images.githubusercontent.com/13456559/44365359-aa9f4780-a51d-11e8-93a3-f3769b6b6eb4.png)

First noticed the 20th and I found logs going back to the 17th when it seems to have started.

> 20/Aug/2018 00:52:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Error in list of partitions to DROP
> 20/Aug/2018 00:52:35 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180522'
> 20/Aug/2018 00:52:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Error in list of partitions to DROP
> 20/Aug/2018 00:52:35 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180522'
> 20/Aug/2018 00:52:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Error in list of partitions to DROP
> 20/Aug/2018 00:52:35 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180522'
> 20/Aug/2018 00:52:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Error in list of partitions to DROP
> 20/Aug/2018 00:52:35 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180522'
> 20/Aug/2018 00:52:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Error in list of partitions to DROP
> 20/Aug/2018 00:52:35 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180522'
> 20/Aug/2018 00:52:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Error in list of partitions to DROP
> 20/Aug/2018 00:52:35 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180522'
> 20/Aug/2018 00:52:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Error in list of partitions to DROP
> 20/Aug/2018 00:52:35 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180522'
> 20/Aug/2018 00:52:35 - CMDPHP ERROR: A DB Exec Failed!, Error: Error in list of partitions to DROP

> 17/Aug/2018 00:02:26 - DBCALL ERROR: A DB Exec Failed!, Error:1517, SQL:'ALTER TABLE `syslog`.`syslog` REORGANIZE PARTITION dMaxValue INTO ( PARTITION d20180817 VALUES LESS THAN (TO_DAYS('2018-08-18')), PARTITION dMaxValue VALUES LESS THAN MAXVALUE)'
> 17/Aug/2018 00:02:26 - DBCALL ERROR: A DB Exec Failed!, Error:1517, SQL:'ALTER TABLE `syslog`.`syslog` REORGANIZE PARTITION dMaxValue INTO ( PARTITION d20180817 VALUES LESS THAN (TO_DAYS('2018-08-18')), PARTITION dMaxValue VALUES LESS THAN MAXVALUE)'

> Log [Total Lines: 3 - Admin View - Additional Filter in Affect]
> 18/Aug/2018 00:03:52 - DBCALL ERROR: A DB Exec Failed!, Error:1517, SQL:'ALTER TABLE `syslog`.`syslog` REORGANIZE PARTITION dMaxValue INTO ( PARTITION d20180818 VALUES LESS THAN (TO_DAYS('2018-08-19')), PARTITION dMaxValue VALUES LESS THAN MAXVALUE)'
> 18/Aug/2018 00:03:52 - DBCALL ERROR: A DB Exec Failed!, Error:1517, SQL:'ALTER TABLE `syslog`.`syslog` REORGANIZE PARTITION dMaxValue INTO ( PARTITION d20180818 VALUES LESS THAN (TO_DAYS('2018-08-19')), PARTITION dMaxValue VALUES LESS THAN MAXVALUE)'
> 18/Aug/2018 00:03:52 - DBCALL ERROR: A DB Exec Failed!, Error:1517, SQL:'ALTER TABLE `syslog`.`syslog` REORGANIZE PARTITION dMaxValue INTO ( PARTITION d20180818 VALUES LESS THAN (TO_DAYS('2018-08-19')), PARTITION dMaxValue VALUES LESS THAN MAXVALUE)'

> Log [Total Lines: 1489 - Admin View - No Other Filter in Affect]
> 17/Aug/2018 00:03:27 - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 159 syslog_partition_manage)(/plugins/syslog/functions.php: 114 syslog_partition_remove)(/plugins/syslog/functions.php: 166 syslog_db_execute)(/plugins/syslog/database.php: 52 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
> 17/Aug/2018 00:03:27 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180519'
> 17/Aug/2018 00:03:27 - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 159 syslog_partition_manage)(/plugins/syslog/functions.php: 114 syslog_partition_remove)(/plugins/syslog/functions.php: 166 syslog_db_execute)(/plugins/syslog/database.php: 52 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
> 17/Aug/2018 00:03:27 - DBCALL ERROR: A DB Exec Failed!, Error:1507, SQL:'ALTER TABLE `syslog`.`syslog` DROP PARTITION d20180519'
> 17/Aug/2018 00:03:27 - SYSTEM SYSLOG STATS:Time:595.89 Deletes:0 Incoming:37 Removes:0 XFers:37 Alerts:19 Alarms:17 Reports:4
> 17/Aug/2018 00:03:27 - SYSLOG WARNING: The Syslog Intance Alert 'Cisco DHCP Snooping Alerts' with Severity 'Warning', has been Triggered, Count was '20', and Sequence '2812'
> 17/Aug/2018 00:02:26 - SYSTEM SYSLOG: Removing old partition 'dd20180519'
> 17/Aug/2018 00:02:26 - SYSTEM SYSLOG: Removing old partition 'dd20180519'
> 17/Aug/2018 00:02:26 - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 159 syslog_partition_manage)(/plugins/syslog/functions.php: 113 syslog_partition_create)(/plugins/syslog/functions.php: 140 syslog_db_execute)(/plugins/syslog/database.php: 52 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
> 17/Aug/2018 00:02:26 - DBCALL ERROR: A DB Exec Failed!, Error:1517, SQL:'ALTER TABLE `syslog`.`syslog` REORGANIZE PARTITION dMaxValue INTO ( PARTITION d20180817 VALUES LESS THAN (TO_DAYS('2018-08-18')), PARTITION dMaxValue VALUES LESS THAN MAXVALUE)'
> 17/Aug/2018 00:02:26 - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 159 syslog_partition_manage)(/plugins/syslog/functions.php: 113 syslog_partition_create)(/plugins/syslog/functions.php: 140 syslog_db_execute)(/plugins/syslog/database.php: 52 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
> 17/Aug/2018 00:02:26 - DBCALL ERROR: A DB Exec Failed!, Error:1517, SQL:'ALTER TABLE `syslog`.`syslog` REORGANIZE PARTITION dMaxValue INTO ( PARTITION d20180817 VALUES LESS THAN (TO_DAYS('2018-08-18')), PARTITION dMaxValue VALUES LESS THAN MAXVALUE)'
> 17/Aug/2018 00:02:26 - SYSTEM SYSLOG STATS:Time:321.83 Deletes:0 Incoming:14 Removes:3 XFers:0 Alerts:19 Alarms:0 Reports:4
> 17/Aug/2018 00:02:26 - SYSTEM SYSLOG: Removing old partition 'dd20180519'
> 17/Aug/2018 00:02:05 - SYSTEM SYSLOG: Creating new partition 'd20180817'
> 17/Aug/2018 00:01:24 - SYSTEM SYSLOG STATS:Time:367.35 Deletes:0 Incoming:1 Removes:0 XFers:1 Alerts:19 Alarms:0 Reports:4
> 17/Aug/2018 00:01:23 - SYSLOG WARNING: The Syslog Intance Alert 'Cisco DHCP Snooping Alerts' with Severity 'Warning', has been Triggered, Count was '14', and Sequence '2811'
> 17/Aug/2018 00:01:23 - SYSTEM SYSLOG STATS:Time:424.15 Deletes:0 Incoming:0 Removes:0 XFers:0 Alerts:19 Alarms:0 Reports:4
> 17/Aug/2018 00:00:58 - SYSTEM SYSLOG: Creating new partition 'd20180817'
> 17/Aug/2018 00:00:15 - SYSTEM SYSLOG: Creating new partition 'd20180817'

Then when I tried to enable it again 

> 20/Aug/2018 16:02:06 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/syslog/syslog_counter.php: 47 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
> 20/Aug/2018 16:02:06 - ERROR PHP NOTICE in Plugin 'syslog': Undefined index: Auto_increment in file: /usr/share/cacti-1.1.37/plugins/syslog/syslog_counter.php on line: 47
> 20/Aug/2018 16:02:06 - CMDPHP PHP ERROR NOTICE Backtrace: (/plugins/syslog/syslog_counter.php: 44 CactiErrorHandler)(/lib/functions.php: 4590 cacti_debug_backtrace)
> 20/Aug/2018 16:02:06 - ERROR PHP NOTICE in Plugin 'syslog': Undefined index: Auto_increment in file: /usr/share/cacti-1.1.37/plugins/syslog/syslog_counter.php on line: 44

So it seems that there isn't a way to recover from this state.

It's a bit of a pain because you've got to re create all the rules.

**Comment by jpobeda** [comment]
I just realized there is a nice option when uninstalling the plugin to remove everything or data only. 

That saves you from creating alert/removal/reports rules again. It's always a pain to lose historical data.

I'm going to give it another go using traditional table this time. It's only around 50-60 devices sending syslog messages so it shouldn't be that hard to handle it.

**Comment by cigamit** [comment]
Did this happen to happen on the start of daylight savings time?  I suspect that is the issue.

**Comment by cigamit** [comment]
@jpobeda, this should be resolved now.

**Comment by jpobeda** [comment]
@cigamit , thanks I have actually switched to traditional tables and haven't had any issues so far. I'll give it a go some time this year. Can't promise though. I'll open a new issue and link it to this one if it doesn't work.

**Comment by jpobeda** [comment]
@cigamit btw

```Call to undefined function cacti_sizeof() in /usr/share/cacti-1.1.37/plugins/syslog/setup.php on line 194```

forgot to include cacti's function somewhere?

**Comment by netniV** [comment]
Cacti_Sizeof is a 1.2 workaround for php 7.2
