### ISSUE TITLE
Cacti 1.2.0 Latest - Syslog Latest - graphics bug

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_syslog#54]
![image](https://user-images.githubusercontent.com/11805503/44458112-d3066f00-a60d-11e8-881a-9673ae5a50e8.png)
the drop-down list icon is out of place

**Comment by netniV** [comment]
What version of cacti is that running under?  If it's 1.2, it's probably a compatibility issue due to the updates to themes so will be covered when we do the plugin review after the beta is started.

**Comment by pautiina** [comment]
Today's version, from develop branch :)
Well, we'll wait for the output of the stable version of Cacti 1.2.0.

**Comment by netniV** [comment]
I was meaning the Core.

**Comment by pautiina** [comment]
Resolved
