### ISSUE TITLE
Syslog 2.1 database table population issue with new template

### ISSUE THREAD

**Issue by fiznuckle** [Cacti/plugin_syslog#55]
Per Cacti Guru User, I am putting in this issue:

Was having an issue with the proper tables being updated in syslog v2.1 while running Cacti v1.1.38.  I kept receiving "db error (1054): Unknown column' errors in my database and all my syslogs were going into my SystemEvents table.

I followed the install direction on Github @ https://github.com/Cacti/plugin_syslog regarding the cacti.conf file in the rsyslog dir, but did nothing. I ended up having to copy "$template cacti_syslog,"INSERT INTO syslog_incoming(facility_id, priority_id, program, date, time, host, message) \
values (%syslogfacility%, %syslogpriority%, '%programname%', '%timereported:::date-mysql%', '%timereported:::date-mysql%', '%HOSTNAME%', TRIM('%msg%'))", SQL" from the cacti.conf file and add this direclty to my rsyslog.conf file.

Here is a link back to the original thread:
https://forums.cacti.net/viewtopic.php?f=21&t=59097

**Comment by netniV** [comment]
What is the operating system and version you are running on?  This may need to be a documentation note as the cacti.conf file for syslog should work if the system is including configuration files from a conf.d type directory.

**Comment by fiznuckle** [comment]
CentOS Linux release 7.2.1511 (Core)

**Comment by cigamit** [comment]
Perform a describe on the syslog_incoming table.  My guess is that the columns are not correct.

**Comment by cigamit** [comment]
Closing this.  Worked fine with CentOS for me today using the instructions in the README.md
