### ISSUE TITLE
[develop] when calling the function syslog_log_alert() an error occurs in the log like

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_syslog#56]
```
2018/10/04 16:19:12 - SYSLOG WARNING: The Syslog Intance Alert 'Unauthenticated IP-MAC' with Severity 'Notice', has been Triggered, Count was '25', and Sequence ''
--
2018/10/04 16:19:12 - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php[420]:syslog_log_alert(), /plugins/syslog/functions.php[664]:syslog_sql_save(), /plugins/syslog/database.php[129]:sql_save())
2018/10/04 16:19:12 - DBCALL ERROR: SQL Save on table '`cacti`.`syslog_logs`': Table does not exist, unable to save!

```
But everything works and the table exists.

**Comment by pautiina** [comment]
@netniV is an explanation of what I saw in the script?

**Comment by netniV** [comment]
This error means that you have something trying to write to the syslog table but it may be in its own database no the cacti one?

**Comment by pautiina** [comment]
I,m use cacti.syog_* databese and table.
I think problem on https://github.com/Cacti/plugin_syslog/blob/8495c35e3648091bc8821875d3b900df11ae58c9/database.php#L127 
The rest is working. The call to this function is found only in two places.

**Comment by netniV** [comment]
No I think it’s higher up. I think the table name has an extra S maybe? I’m on my iPad so not looking at a dB

**Comment by netniV** [comment]
I’m convinced. Do a PR for it if you can.

**Comment by netniV** [comment]
Why? It’s the table name it’s being told to use that’s wrong, not the function.

**Comment by netniV** [comment]
https://github.com/Cacti/plugin_syslog/blob/8495c35e3648091bc8821875d3b900df11ae58c9/functions.php#L646

**Comment by pautiina** [comment]
But the table exists, and the error pops up

**Comment by netniV** [comment]
Are you sure? The table should by syslog not syslog?

**Comment by netniV** [comment]
Syslogs even

**Comment by pautiina** [comment]
Yes I am sure.
![image](https://user-images.githubusercontent.com/11805503/46559198-3ca9b680-c8f8-11e8-8b7a-50ffaad13cb3.png)

**Comment by netniV** [comment]
Look at the table name and then look at the line I linked.

**Comment by netniV** [comment]
Your screenshot proves me right :)

**Comment by pautiina** [comment]
Where exactly are you right? Show me in the screenshot

**Comment by netniV** [comment]
The table name in the link I linked is wrong, it has too many letters. Your screenshot has 6, the code has 7

**Comment by netniV** [comment]
Leave it with me, I’ll review it properly shortly

**Comment by pautiina** [comment]
@netniV Although kill me - I do not see the difference :(

**Comment by netniV** [comment]
You could be right as I was looking on a tiny screen.  But I'll review now I have my laptop rather than just assume 👍

**Comment by netniV** [comment]
Right, I'm just going to remove all our previous messages and create a new issue on Cacti Core as there's an issue with 1.2 with the db_table_exists() function which SQL_SAVE now uses to verify the save before it begins.

**Comment by netniV** [comment]
OK issue has been created.

**Comment by netniV** [comment]
I've added a patch to the core db_table_exists function for this.  There probably needs to be another one for the column/index exists.

**Comment by pautiina** [comment]
Fixed on https://github.com/Cacti/cacti/issues/2015
