### ISSUE TITLE
syslog 2.1 - setup.php doesn't create tables syslog and syslog_logs. 

### ISSUE THREAD

**Issue by sd3m0n** [Cacti/plugin_syslog#59]
Setup.php doesn't create tables syslog and syslog_logs. They both have default values like zero dates in timestamp fields. Yes I have mysql >5.7 with NO_ZERO_DATE and NO_ZERO_IN_DATES. I'm sure that the problem is here. So question... Is it really needed to remove this flags from mysql conf, or there is another solution?

**Comment by sd3m0n** [comment]
So, after reading all posts on all issues here I came to the conclusion that the only right solution is to set
`sql_mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
Of course I can change the defaults to smth like `1970-01-02 ...` but this will need to edit source files. Ok, I think it can be closed for now.

**Comment by cigamit** [comment]
I have updated the documentation in this commit to add this step.  https://github.com/Cacti/plugin_syslog/commit/c664783a07aa064affa543b79bde808b6ccecc7a

**Comment by sd3m0n** [comment]
Thnx. That should really help to fasten the installation process instead of researching logs and sources.
