### ISSUE TITLE
[v2.1] TypeError: position is undefined

### ISSUE THREAD

**Issue by ycaoxa** [Cacti/plugin_syslog#63]
install&enable syslog plugin(v2.1 ),go to its page ,then to my another page,It shows blank . the error thrown out in firefox concole as below:
TypeError: position is undefined

 Code issue in syslog.php:
 function resizeHostSelect() {

                        position = $('#host').offset();
                        $('#host').css('height', ($(window).height()-position.top)+'px');
              }

Fixed like :
 function resizeHostSelect() {
             if($('#host') && $('#host').offset()){
                        position = $('#host').offset();
                        $('#host').css('height', ($(window).height()-position.top)+'px');
              }
        }

please help to review and fix it in next release , thanks

**Comment by cigamit** [comment]
I think this code can be safely removed.  Pretty sure it has been in latest develop.

**Comment by cigamit** [comment]
We are no longer supporting this version of syslog.
