### ISSUE TITLE
setup.php does not create hash columns required.

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_syslog#64]
I had to manually create the columns after upgrade so I could edit alert rules.

> ALTER TABLE `syslog_alert` ADD `hash` VARCHAR(32) NULL AFTER `id`;
ALTER TABLE `syslog_remove` ADD `hash` VARCHAR(32) NULL AFTER `id`;
ALTER TABLE `syslog_reports` ADD `hash` VARCHAR(32) NULL AFTER `id`;

**Comment by cigamit** [comment]
Wrong syntax Dan

`ALTER TABLE syslog_alert ADD COLUMN hash VARCHAR(32) NOT NULL default '' AFTER id;`
`...`

**Comment by jdcoats** [comment]
I did go back and change that after looking at the setup.php, thanks for confirming


——
Dan

**Comment by cigamit** [comment]
Going to go ahead and close this one.
