### ISSUE TITLE
MySQL failures due to large amount of syslog data

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_syslog#65]
So Ive been using this plugin for many years. Since upgrading to 1.x I've been having an issue where syslog would run fine for a day and then blow up. It has been that I would find that mysql would be saying that many tables were full. I would have to kill a bunch of hung php syslog_processes and truncate syslog, syslog_incoming, syslog_removed, & syslog_logs to recover. I thought that it was a memory issue, so yesterday I threw another 30G of ram at mysql with hope that would resolve it. The problem still exists, Ive just made it so that it doesnt take down mysql all together now. I do not know what makes it rune fine for many hours and then all of a sudden start doing this. Help with a clue where to start? This is a very busy syslogtomysql where just the 4 ASA firewalls will produce 1GB+per day. I am removing more than I keep.
[syslog.txt](https://github.com/Cacti/plugin_syslog/files/2865187/syslog.txt)

**Comment by netniV** [comment]
Whilst I may not know much about the plugin, I think I've addressed the title issue ;-)

**Comment by jdcoats** [comment]
I think that I found the culprit. Ive had a cronjob for years that runs mysqlfragfinder.sh @daily. This process makes the syslog_process.php hang up waiting and never completes.

> root      2200  0.0  0.0  47660  4676 ?        S    00:09   0:00 mysql -uroot -px xxxxxxxx -h127.0.0.1 -D syslog --skip-column-names --batch -e optimize table syslog_incoming

Ill stop the cronjob until I can force it to ignore trying to optimize syslog_incoming which is so busy that it may be impossible for it to finish. You can close this a user inflicted pain :)

**Comment by jdcoats** [comment]
I guess I spoke too soon. The above wasn't the problem, I guess it was just another symptom, the optimize table process was just another thing getting hung along with all of the syslog_process.php's for each subsequent polling cycle. Still trying to find the culprit. I have found out that I do not have to do anything to the db, just killall -9 php to clean the processing gets everything started again.

**Comment by netniV** [comment]
You should be able to query which process is locking / blocking.

**Comment by jdcoats** [comment]
I'm not sure

**Comment by cigamit** [comment]
I would enable the slow query log, and also do a "show processlist" in mysql to see what is hanging.

**Comment by cigamit** [comment]
There is a memory limit in one of the plugins, think it's nectar.  We should make that a global.

**Comment by cigamit** [comment]
@jdcoats, if you find the process hung, then please perform an strace.  I'm wondering if multiple syslog processes are stacking up due to your data collection interval.  If you can confirm that, then we have a pretty good chance of resolving.

**Comment by jdcoats** [comment]
This issue was resolved after I moved to ssd disks. I know it doesn’t help those without but I can no longer reproduce. I’m thinking it had to do with the amount of syslog data I was piping in the the write speed. I’m sending an enormous amount of syslog data to it with MySQL on the same cacti host. The ASAs will send what equates to 7gb a day plus the hundreds of other devices sending syslogs. So in the end only keeping 1 day and ssds resolved it. I just grep raw logs for anything I really need to search or filter for and use the plugin simply for email alert notifications in real time.


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On April 24, 2019 at 8:34:50 PM EDT, Jimmy Conner <notifications@github.com> wrote:
CAUTION! This email came from outside Tallahassee Memorial HealthCare. Exercise extra caution clicking links and opening attachments from any and all senders.



________________________________

@jdcoats<https://github.com/jdcoats>, if you find the process hung, then please perform an strace. I'm wondering if multiple syslog processes are stacking up due to your data collection interval. If you can confirm that, then we have a pretty good chance of resolving.

**Comment by TheWitness** [comment]
MariaDB has some real nice features for rapid search, but it's a pretty big change and pretty much kicks MySQL out of the game.  One of the best ways to improve search performance is by providing Shard Queries, which are available in MaxScale.  MariaDB should bring that feature into standard MariaDB in my opinion.  It works great on partitioned tables.

**Comment by TheWitness** [comment]
Additionally, I've observed at a few customer sites, that syslog has no process interlock.  So, you can have multiple 'syslog-process.php' script running concurrently if you have some database slowdown, and at that point, the system just hangs, and next thing you know, you've got 20m records in the syslog_incoming table and have to purge it to get syslog running again.  I suspect this is the same problem.

**Comment by TheWitness** [comment]
I've added a 'cleanup' to the syslog_incoming table now.  That'll keep it from growing due to failed polling.
