### ISSUE TITLE
syslog.php in line 1038 

### ISSUE THREAD

**Issue by hel2o** [Cacti/plugin_syslog#7]
$hosts = syslog_db_fetch_assoc("SELECT host_id, SUBSTRING_INDEX(host,'.',1) AS host FROM `" . $syslogdb_default . "`.`syslog_hosts` $hosts_where ORDER BY host");
when the host is an ipaddress in the syslog display is not normal;
mybe change like this
$hosts = syslog_db_fetch_assoc("SELECT host_id, host AS host FROM `" . $syslogdb_default . "`.`syslog_hosts` $hosts_where ORDER BY host");

**Comment by cigamit** [comment]
Resolved.
