### ISSUE TITLE
color of emergency info incorrect 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_syslog#70]
Problem1: color of emergency info incorrect 

 Go to syslog, check emergency log info, color not correct. 
![Screen Shot 2019-04-04 at 4 05 10 PM](https://user-images.githubusercontent.com/47589910/55539863-45871380-56f4-11e9-9914-f9e7423b749d.png)

cacti 1.2.3 
rhel73 x64
FF

**Comment by cigamit** [comment]
This was a Cacti issue, but will be resolved in 1.2.4.
