### ISSUE TITLE
Export alert log has sql error 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_syslog#71]
1) Go to syslog - Alert log tab 
2) Click export to export data
3) Check log, error exist 

2019/04/04  16:50:30 - CMDPHP PHP ERROR NOTICE Backtrace:   (/plugins/syslog/syslog.php[84]:syslog_export(),  /plugins/syslog/functions.php[608]:CactiErrorHandler())

2019/04/04 16:50:30 - ERROR PHP NOTICE in  Plugin 'syslog':  Undefined index:  in file: /opt/IBM/cacti/plugins/syslog/functions.php   on line: 608

![Screen Shot 2019-04-04 at 4 53 24 PM](https://user-images.githubusercontent.com/47589910/55542859-8550f980-56fa-11e9-8adb-eba903e95e82.png)

cacti 1.2.3 
FF
rhel73 x64

**Comment by cigamit** [comment]
Resolved.

**Comment by yingbaiibm** [comment]
passed retest
