### ISSUE TITLE
Graph Template not workable after import by cli/import_template.php

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_syslog#72]
1.  Import graph template:
`php -q cli/import_template.php --filename=plugins/syslog/template/cacti_graph_template_localhost_syslog_messages.xml --with-profile`
or
`php -q cli/import_template.php --filename=plugins/syslog/template/cacti_graph_template_localhost_syslog_messages.xml`

2. Associate graph template "Localhost - Syslog Messages" to "Local Linux Machine"
3. Check graph after a round poller interval:
    "Trun On Graph Debug Mode", and HTTP Error Log" show error below:
```log
ERROR: bad format for GPRINT in 'Current:'
ERROR: bad format for GPRINT in 'Average:'
ERROR: bad format for GPRINT in 'Max:\n'
ERROR: bad format for GPRINT in 'Max:'
```

**Comment by cigamit** [comment]
Resolved.
