### ISSUE TITLE
Gap to Cacti 1.x:  Syslog missed to support database ssl

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_syslog#73]
In Cacti 1.x,  db_connection support SSL by:
```
$database_ssl      = false;
$database_ssl_key  = '';
$database_ssl_cert = '';
$database_ssl_ca   = '';
```
But,  syslog_process.php does not support database_ssl when db_connect_real

**Comment by cigamit** [comment]
This issue is resolved.  Closed when satisfied.
