### ISSUE TITLE
All Progarms not show anything using Classic theme

### ISSUE THREAD

**Issue by kanzone** [Cacti/plugin_syslog#84]
I found that the "All Programs" value show as "0" instead of "-1".
After I change the vaule to "-1" and "All Programs" is working well.

![cacti](https://user-images.githubusercontent.com/255356/59238726-a7528500-8c31-11e9-9a74-3271e8c0cca9.png)
![cacti2](https://user-images.githubusercontent.com/255356/59238727-a7eb1b80-8c31-11e9-9c97-ca5fd74bd40e.png)

**Comment by cigamit** [comment]
Resolved, thanks!
