### ISSUE TITLE
some color in syslog bar are the same 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_syslog#85]
**To Reproduce**
1) Install newest cacti 1.2.4 and syslog 
2) Go to syslog page 
3) Check color of different level , the emergency, critical and Alert color are the same 

**Expected behavior**
1) The color for each priority are different and easy to identify 
2) Need fix on each theme 

**Screenshots**
![Screen Shot 2019-06-12 at 4 15 15 PM](https://user-images.githubusercontent.com/47589910/59335923-229a6080-8d30-11e9-814d-c333e9d4e472.png)

cacti 1.2.3
FF
rhel7 x64 
syslog 2.2

**Comment by yingbaiibm** [comment]
@netniV   I logged similar color bug before (https://github.com/Cacti/plugin_syslog/issues/70)  in syslog area and  cigamit  said this is cacti issue.  
Now I found this issue is not perfectly resolved, so I logged this bug in cacti area.

**Comment by ddb4github** [comment]
> This should be on the syslog plugin section

Actually, related classes are defined in cacti/include/theme/*/main.css with name logXxxxxx

**Comment by cigamit** [comment]
Correct, this would be a Cacti bug since the log themes are in the core due to their dual use.  Closing here.  They are not the same color, but they are close.
