### ISSUE TITLE
No color for emergency item 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_syslog#86]
Go to syslog - system logs page to check emergency log color, no color for it.  -- failed. 
![Screen Shot 2019-06-13 at 4 55 03 PM](https://user-images.githubusercontent.com/47589910/59418977-8db16900-8dfc-11e9-8af8-f4d2413f56e8.png)

related code 
./syslog/functions.php:552:             $class = 'logEmerg';
./syslog/syslog.php:1435:       print "<td width='10%' class='logEmergency'>" . __('Emergency', 'syslog') . '</td>';

cacti 1.2.4 
syslog 2.2

**Comment by cigamit** [comment]
Resolved, thanks!

**Comment by yingbaiibm** [comment]
passed retest
