### ISSUE TITLE
404 not found error due to incorrect URL request 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_syslog#87]
1) Go to syslog.php page 
2) Go to Thold page 
After a while, will have popup windows show 404 not found for page xxxx. Check http error like below. 

[Thu Jun 13 17:14:13.766206 2019] [:error] [pid 15770] [client 9.197.116.30:55452] script '/var/www/html/cacti/plugins/thold/syslog.php' not found or unable to stat, referer: http://9.111.250.152/cacti/plugins/thold/thold_graph.php

**Comment by cigamit** [comment]
This is a neither a thold or syslog bug.  It must be a third party bug.
