### ISSUE TITLE
Provide text color to indicate device status in Cacti

### ISSUE THREAD

**Issue by Kirandp6** [Cacti/plugin_syslog#88]
Hi Team

Pls enable an icon next to server which reports in cacti with syslog , Green or Red icon will help. 

Green = Server is reporting syslog in cacti perfectly 
Red = Server is not reporting syslog into cacti ( may be server down or rsyslog ( redhat ) say is down. File uploaded for ref. 

Thanks 
![cacti-1x](https://user-images.githubusercontent.com/51837573/59538108-8d24db00-8ead-11e9-8ea8-d76657f56e28.JPG)

**Comment by cigamit** [comment]
Nice idea.  This is the old user interface, we can consider it for a future release though.
