### ISSUE TITLE
Page become blank after collecting multiple host syslog info 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_syslog#91]
1) Set rsyslog remote host collection in rsyslog.conf in remote host 
problem1: 
2) Go to syslog page, choose multiple device, page show blank --- failed 

(/plugins/syslog/syslog.php[98]:syslog_messages(),  /plugins/syslog/syslog.php[1492]:get_syslog_messages(),  /plugins/syslog/syslog.php[807]:sql_hosts_where(),  /plugins/syslog/functions.php[590]:input_validate_input_number(),  /lib/html_validate.php[33]:die_html_input_error(),  /lib/html_validate.php[64]:cacti_debug_backtrace())

![Screen Shot 2019-06-18 at 4 46 17 PM](https://user-images.githubusercontent.com/47589910/59667058-a9e04c00-91e8-11e9-9dcf-5b7955dd8b30.png)

**Comment by cigamit** [comment]
This has been resolved.

**Comment by yingbaiibm** [comment]
passed retest
