### ISSUE TITLE
Export table empty 

### ISSUE THREAD

**Issue by yingbaiibm** [Cacti/plugin_syslog#92]
1) Go to syslog page 
2) Change device filter to see remote host (IP9-111-250-152) syslog info, since remote host time is later then localhost, no info display for current timespan 
3) Change timespan to able to show remote host rsyslog info 
4) Do export, no info show 
![Screen Shot 2019-06-19 at 2 40 03 PM](https://user-images.githubusercontent.com/47589910/59743015-9a710980-92a1-11e9-9f40-8ae4bd7b1000.png)
![Screen Shot 2019-06-19 at 2 41 02 PM](https://user-images.githubusercontent.com/47589910/59743019-9c3acd00-92a1-11e9-8641-1098c1c2864f.png)
![Screen Shot 2019-06-19 at 2 50 03 PM](https://user-images.githubusercontent.com/47589910/59743022-9e049080-92a1-11e9-881e-8a232aa4d0fe.png)

cacti 1.2.4 
syslog 2.2
FF

**Comment by cigamit** [comment]
The syslog service on the client needs to set the correct timezone of the syslog server that it's forwarding to.  This is more of a documentation issue than a functional issue.

**Comment by cigamit** [comment]
After reviewing the latest rsyslog documentation, it appears that they have removed the timezone setting.  So, this will have to be handled by a design change to the syslog plugin.

**Comment by TheWitness** [comment]
This was effectively resolved in an update to the install documentation to use the generated date vs. the date forwarded by the client in the structure of /etc/rsyslog.d/cacti.conf.

As a result, I'm going to mark this resolved.

**Comment by TheWitness** [comment]
For reference, there were two commits:

https://github.com/Cacti/plugin_syslog/commit/62426cdeeaba9b25d24273eb48a86deedf80b9cb#diff-04c6e90faac2675aa89e2176d2eec7d8

and

https://github.com/Cacti/plugin_syslog/commit/2038a3eab7a29c9caac76b3cb3ecade82b02a649#diff-04c6e90faac2675aa89e2176d2eec7d8
