### ISSUE TITLE
CMDPHP Validation Error Backtrace

### ISSUE THREAD

**Issue by hxbzh021** [Cacti/plugin_syslog#93]
When "cacti/plugins/syslog/syslog.php" selects two devices at the same time, the following error will be reported. Please help me to see what is the problem?

Error Backtrace: (/var/lib/cacti/plugins/syslog/syslog.php[98]:syslog_messages(), /var/lib/cacti/plugins/syslog/syslog.php[1492]:get_syslog_messages(), /var/lib/cacti/plugins/syslog/syslog.php[807]:sql_hosts_where(), /var/lib/cacti/plugins/syslog/functions.php[590]:input_validate_input_number(), /lib/html_validate.php[33]:die_html_input_error(), /lib/html_validate.php[64]:cacti_debug_backtrace())

**Comment by cigamit** [comment]
This has already been resolved in develop.  Update to the latest develop and this issue will be resolved.

**Comment by hxbzh021** [comment]
It has indeed been resolved, thank you very much.
