### ISSUE TITLE
Stored XSS in syslog_removal.php

### ISSUE THREAD

**Issue by ddb4github** [Cacti/plugin_syslog#94]
![image](https://user-images.githubusercontent.com/17589018/60055184-59e51600-970f-11e9-86b4-9c66154d1764.png)

![image](https://user-images.githubusercontent.com/17589018/60055119-20aca600-970f-11e9-9f32-0d24d7bf9bb2.png)

![image](https://user-images.githubusercontent.com/17589018/60055156-446fec00-970f-11e9-8e7f-129bba9e5f91.png)

**Comment by cigamit** [comment]
Resolved.
