### ISSUE TITLE
cacti 1.2.7 + Syslog having multiple PHP errors 

### ISSUE THREAD

**Issue by bmfmancini** [Cacti/plugin_syslog#98]
Hey All 

I am seeing the following errors 

Currently I am not able to see any of the syslog messges in the browser although they seem populated in the DB so I  am thinking these errors may have something to do with it 

This is a fresh cacti install 

 php -q syslog_process.php --debug --force-report
PHP Warning:  include(./include/cli_check.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 25
PHP Warning:  include(): Failed opening './include/cli_check.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 25
PHP Warning:  include_once(./lib/poller.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 26
PHP Warning:  include_once(): Failed opening './lib/poller.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 26
PHP Warning:  include(./plugins/syslog/config.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 27
PHP Warning:  include(): Failed opening './plugins/syslog/config.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 27
PHP Warning:  include_once(./plugins/syslog/functions.php): failed to open stream: No such file or directory in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 28
PHP Warning:  include_once(): Failed opening './plugins/syslog/functions.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 28
PHP Fatal error:  Uncaught Error: Call to undefined function cacti_sizeof() in /var/www/html/cacti/plugins/syslog/syslog_process.php:45
Stack trace:
#0 {main}
  thrown in /var/www/html/cacti/plugins/syslog/syslog_process.php on line 45

**Comment by bmfmancini** [comment]
Tried to clone from the master repo PHP errors are gone but still not getting any messges in the gui but the tables are filling up properly I have posted this on the forums as well 

I am stumped here 

Also I notice a gui bug from the master repo

tried with Firefox and chrome same deal 

![image](https://user-images.githubusercontent.com/13388748/66087403-5bf81580-e545-11e9-9820-42666c62fcf8.png)

**Comment by netniV** [comment]
I fixed up the directory issue, it's missing a `chdir('../../');` at the top of the script for some reason.  But when I started to test the shell command, it gave other errors so I need to see why.

This isn't a problem of 1.2.7 but more a problem with the syslog_process.php itself.

**Comment by bmfmancini** [comment]
ok cool thanks 

Any idea if there is a compatbility issue  with 1.2.7 for the life of me I cant get messages to display 
but the tables  populate just fine

**Comment by bmfmancini** [comment]
OK I cloned from dev and put chdir('../../'); at the top of the script for now and yes the error is gone 
but still no messages in the message view 

I put all of my config info in the forum post 

https://forums.cacti.net/viewtopic.php?f=2&t=60200

Any help would be appreciated !!

**Comment by bmfmancini** [comment]
I've dou keep checked httpd errors nothing there 
The drop downs populate with the sevices I am monitoring along with the facilities the errors are in but nothing display I'm really stumped on this one

**Comment by bmfmancini** [comment]
more digging I see that syslog does transfer recived alerts into the syslog table 
but nothing on the front end  does anyone have any ideas ?

php syslog_process.php -d
SYSLOG: Syslog Table IS Partitioned
SYSLOG: Unique ID = 119
SYSLOG: Found   0, New Message(s) to process
SYSLOG: Found   0,  Removal Rule(s) to process
SYSLOG: Found   0,  Alert Rules to process
SYSLOG: Moved   135,  Message(s) to the 'syslog' table
SYSLOG: Deleted 135,  Already Processed Message(s) from incoming
SYSLOG: Deleted 0,  Syslog alarm log Record(s)
SYSLOG: Deleted 0,  Syslog Host Record(s)
SYSLOG: Deleted 0,  Old programs from programs table
SYSLOG: Deleted 0,  Syslog Host/Facility Record(s)
SYSLOG: Processing Reports...
SYSLOG: We have 0 Reports in the database
SYSLOG: Finished processing Reports...
2019/10/02 22:50:55 - SYSTEM SYSLOG STATS: Time:0.04 Deletes:0 Incoming:0 Removes:0 XFers:135 Alerts:0 Alarms:0 Reports:0

**Comment by bmfmancini** [comment]
Ok I have no clue as to how this started working aside from the fact that I re-installed rsyslog and copied and pasted the same config  I am wondering if it was just a timing thing ???

Anyway now that its working I am going to  monitor for now and see and I will add this to the documentation repo

**Comment by bmfmancini** [comment]
So this was a date/time issue all along my bad  time was in UTC so the time shift was pretty wide closing

**Comment by vKnmnn** [comment]
@bmfmancini i think this is just like the problems i had (#58), could you please elaborate on the solving of this issue?

**Comment by bmfmancini** [comment]
Hey !

Yea in my case the server time was off so when I was filtering for say the last 30 mins it would take my local pc time atleast that is what I concluded because after I corrected the time on the server all went well

**Comment by vKnmnn** [comment]
ah ok then this has nothing to do with that. thanks for the quick response
